### ISSUE TITLE
Rename-file wrecks namespaces

### ISSUE THREAD

**Issue by Malabarba** [clojure-emacs/refactor-nrepl#101]
I ran `rename-file` for the first time today and here is what happened.

Firstly, the command worked (very nice :)).
Secondly, though, the `ns` form of the file I renamed had a blank line inside it.

    (ns shouter.models.db
      
      (:require [clojure.java.jdbc :as sql]
                [shouter.models.shout :as shout]))

Thirdly, I visited other files that used this namespace, and their `ns` forms lost all indentation.

    (ns shouter.web
    (:require [compojure
    [core :refer [defroutes]]
    [handler :as handler]
    [route :as route]]
    [ring.adapter.jetty :as ring]
    [shouter.controllers.shouts :as shouts]
    [shouter.models.db :as schema]
    [shouter.views.layout :as layout])
    (:gen-class))

**Comment by Malabarba** [comment]
From `nrepl-messages`. I've shortened the file names. Also note that myproj is a symlink to Dropbox/myproj (not sure if this affects anything).

    (--->
      op  "rename-file-or-dir"
      old-path  "/username/Dropbox/myproj/src/shouter/models/migration.clj"
      new-path  "/username/Dropbox/myproj/src/shouter/models/db.clj"
      id  "23"
    )
    (<-
      id  "23"
      status  ("done")
      touched  ("/username/Dropbox/myproj/src/shouter/models/db.clj")
    )
    (--->
      op  "warm-ast-cache"
      id  "24"
    )
    (<-
      ast-statuses  "(shouter.core-test \"OK\" shouter.controllers.shouts \"OK\" shouter.models.migration \"OK\" shouter.models.shout \"OK\" shouter.views.layout \"OK\" shouter.views.shouts \"OK\" shouter.web \"OK\" shouter.models.db \"OK\")"
      id  "24"
      status  ("done")
    )
    (--->
      op  "clean-ns"
      path  "/username/myproj/src/shouter/web.clj"
      id  "25"
    )
    (<-
      id  "25"
      ns  nil  status  ("done")
    )
    (--->
      op  "clean-ns"
      path  "/username/myproj/src/shouter/web.clj"
      id  "26"
    )
    (<-
      id  "26"
      ns  "(ns shouter.web\n(:require [compojure\n[core :refer [defroutes]]\n[handler :as handler]\n[route :as route]]\n[ring.adapter.jetty :as ring]\n[shouter.controllers.shouts :as shouts]\n[shouter.models.db :as schema]\n[shouter.views.layout :as layout])\n(:gen-class))\n"
      status  ("done")
    )
    (--->
      op  "clean-ns"
      path  "/username/myproj/src/shouter/web.clj"
      id  "27"
    )
    (<-
      id  "27"
      ns  "(ns shouter.web\n(:require [compojure\n[core :refer [defroutes]]\n[handler :as handler]\n[route :as route]]\n[ring.adapter.jetty :as ring]\n[shouter.controllers.shouts :as shouts]\n[shouter.models.db :as schema]\n[shouter.views.layout :as layout])\n(:gen-class))\n"
      status  ("done")
    )

**Comment by Malabarba** [comment]
Also not sure if it matters, but the cursor was exactly at the end of the `(ns shouter.models.migration` when I invoked the command.

**Comment by expez** [comment]
Our pretty-printing of namespaces in the middleware is super basic in that it leaves the indentation to the clients.  So after updating the ns forms in the project we return a list of `touched` files for the client to visit and indent.

Clearly this list was incomplete, in that it only returned the name of the file you moved and not all the dependent files as well.

I'm here is the problematic code:

```clj 
(->> affected-files 
     (filter fs/exists?)
     (remove fs/directory?))
```

```clj
;; symlinked dotfile
(.exists (File. "~/.gitconfig"))
;; => false
```
