### ISSUE TITLE
clean-ns fails if the ns form contains a list instead of a vector

### ISSUE THREAD

**Issue by Malabarba** [clojure-emacs/refactor-nrepl#103]
This is a bit of a corner case, not sure if you care about supporting this, but I figured I'd let you know.

The following is a valid (if unusual) `ns` form.

    (ns dry.file
      (:require (clojure [string :as str]
                         [walk :as walk])
                [clojure.java.io :as io]))

Invoking clean-ns yields this exception (and nothing happens)

    java.lang.ClassCastException: clojure.lang.PersistentList cannot be cast to java.lang.String

**Comment by expez** [comment]
Rewriting stuff like this to make the code base more uniform is part of the value proposition this is absolutely something I want to support.  It seems I introduced a regression when I rewrote the code picking apart the ns form.
