### ISSUE TITLE
Exception caused by namespaced keyword

### ISSUE THREAD

**Issue by grammati** [clojure-emacs/refactor-nrepl#106]
Having a namespaced keyword anywhere in a project causes rename-symbol (called via clj-refactor.el) to fail with an exception. Eg:

    RuntimeException: Invalid token: ::bar/thing

Minimal project to reproduce: https://github.com/grammati/refactor-nrepl-ns-kw-bug

The root cause seems to be this behavior of the clojure reader:

    (read-string "::foo/bar")  => exception

**Comment by grammati** [comment]
Related: http://dev.clojure.org/jira/browse/CLJ-1579

**Comment by expez** [comment]
@bronsa Is this something you can work around in `tools.analyzer`?  Perhaps we are using it wrong?

**Comment by Bronsa** [comment]
@expez both `tools.analyzer` and `tools.reader` fully support namespaced keywords assuming the correct ns context is set (meaning *ns* is bound to the current namespace, aliases and required libs are declared), which would require evaluation of the `ns` form.
To work around this you could bind tools.reader's `*alias-map*` to identity, which would make tools.reader read ::foo/bar as :foo/bar.

**Comment by expez** [comment]
> assuming the correct ns context 

Isn't that the job of `analyze-ns`?

Here's the code we use to build the AST:

```clj
(defn- build-ast
  [ns aliases]
  (when (ns-on-cp? ns)
    (binding [ana/macroexpand-1 noop-macroexpand-1
              *file* (-> ns ajutils/ns-resource ajutils/source-path)
              reader/*data-readers* *data-readers*]
      (assoc-in (aj/analyze-ns ns) [0 :alias-info] aliases))))
```

I still need to add `*alias-map* identity` to the binding vector?

**Comment by Bronsa** [comment]
@expez yes, if you use t.a.jvm's analyze-ns it should work out of the box, I'll try to read your code tomorrow to see why it's failing

**Comment by expez** [comment]
@bronsa after looking more closely at this, it turns out the bug is in the part of our code which uses the clj reader while looking for macros.

Sorry about the noise.

**Comment by expez** [comment]
@grammati thanks for the report!  I've pushed a new snapshot to clojars, which should work on your project.
