### ISSUE TITLE
Include cognitect jars from Maven

### ISSUE THREAD

**Issue by plexus** [clojure-emacs/refactor-nrepl#121]
I tried to add a dependency of `transit-cljs` to my project with clj-refactor.el, and couldn't find the artifact. Turns out the reason is transit is under the `com.cognitect` org on Maven Central, and refactor-nrepl also searches `org.clojure`.

Would it make sense to include `com.cognitect` in the maven search?

**Comment by expez** [comment]
Yeah, feel free to open a pull request for this.  The ns where the magic happens is in `artifacts.clj`.

It's possible to get a list of all jars from clojars, but maven central was a bit harder to deal with.  Thankfully the only entity in the clojure world who uses maven central is the cognitect guys.  I find it weird that they don't put their stuff on clojars (too).

**Comment by plexus** [comment]
Thanks for addressing this. I managed to code up a patch but got stuck
doing the tests. Happy it's  fixed!
