### ISSUE TITLE
Wrong coordinates for function used in defrecord

### ISSUE THREAD

**Issue by expez** [clojure-emacs/refactor-nrepl#123]
```
(defrecord RangeSpec [start end step]
  Transformer
  (transformer [this] `(partial update-seq ::next-fn ~start ~end ~step))
  Selector
  (selector [this] `(partial slice ~start ~end ~step)))
```

When I did `cljr-find-usages` on `slice` it returned the coordinates to the start of `defrecord` form.

**Comment by MalloZup** [comment]
autogenerated with https://github.com/MalloZup/doghub:  issue inactive since 450 days. Please update the issue or close it

**Comment by vemv** [comment]
Looks like there's nothing we can do:

> This is just how macroexpansion works. Once a form has macroexpanded, the subforms it macroexpands to have no real line/col info, so we can only use the original form's line/col info.

https://clojure.atlassian.net/browse/TANAL-122
