### ISSUE TITLE
build-artifact? throws NPEs when not using leiningen or boot

### ISSUE THREAD

**Issue by kotarak** [clojure-emacs/refactor-nrepl#124]
Not using one of the named systems causes NPEs being thrown in the repl, for example when typing a namespaced keyword. Obviously `build-artifact?` fails to check for `nil` in [line 60 of core.clj](https://github.com/clojure-emacs/refactor-nrepl/blob/df84b7a5fd303c1d84adece49834d6446f9c50a4/src/refactor_nrepl/core.clj#L60).

`project-root` fails to identify the project root correctly because it does only look for [`project.clj` or `build.boot`](https://github.com/clojure-emacs/refactor-nrepl/blob/df84b7a5fd303c1d84adece49834d6446f9c50a4/src/refactor_nrepl/core.clj#L43). From the top of my head I could imagine other sensible values like `.project`, `build.gradle`, `pom.xml`, `.git`, `.hg` or `_darcs`.

On the one hand this list is not exhaustive. On the other hand none of them might indicate the true root of the system. So some possibility to hook into that logic would be nice.

(At the moment I monkey patch `project-root` to `(contantly (System/getProperty "user.dir"))`, but that feels rather dirty.)

**Comment by benedekfazekas** [comment]
any chance you can put together a PR for this?

**Comment by kotarak** [comment]
Well, it depends on your strategy for this.

Adding at least `build.gradle` and `pom.xml` is faster done directly than creating a PR. Anything more involved requires some discussion on the "if" and (if yes) the "how", I guess.

I personally can also live with the monkey patch, if the decision is that the majority of the users don't have this problem.

**Comment by expez** [comment]
Why would you ever want to write clojure without using either lein or boot?

**Comment by kotarak** [comment]
Because company policy doesn't allow?

**Comment by bbatsov** [comment]
Probably CIDER itself needs to add some basic support for Maven and Gradle - e.g. `cider-jack-in` should work with them out of the box.

**Comment by benedekfazekas** [comment]
you are right about gradle and pom. I would only prefer PR exactly because this needs some discussion. Always easier to reason about a problem if there is code around it. Appreciate if you think this is a waste of time

**Comment by kotarak** [comment]
@bbatsov you can ping me for the basic requirements regarding gradle for that.

**Comment by expez** [comment]
Supporting both boot and leiningen is as far as I'm willing to go.  I don't want to have to think about maven, ant, gradle and whatever other build systems people might be using.  Even now, boot support is spotty because the API is slightly different.  

I'm fine with fixing this issue, but that's likely just going to be the beginning of your problems.  Your situation is somewhat unique, so it doesn't make much sense spending time, or inflating the code base, to support it.

**Comment by kotarak** [comment]
Fair decision.
