### ISSUE TITLE
Find unused-defs in ns

### ISSUE THREAD

**Issue by sgrove** [clojure-emacs/refactor-nrepl#130]
It would be nice for cleaning up a namespace if I was able to get a list of unused top-level defs for a ns (e.g. not used anywhere in the project). An inefficient implementation could be along the lines of `(filter #(zero? (count (find-usage %))) top-level-symbols)`.

Just proposing this here, let me know if it's the incorrect place.

**Comment by benedekfazekas** [comment]
nice idea! I just wonder if this would not be better placed in
flycheck-clojure/Eastwood unless you want to do something with them, bulk
remove for example...

**Comment by expez** [comment]
@sgrove you might want to check out [sniper](https://github.com/w01fe/sniper), which does just this.
