### ISSUE TITLE
Error when using data_readers.clj

### ISSUE THREAD

**Issue by scramjet** [clojure-emacs/refactor-nrepl#131]
Some of my Clojure source files require custom data readers, which are defined in `src/data_readers.clj`. When trying to refactor (e.g. rename a symbol) I get an error like `No ns form at /Users/matt/Development/.../data_readers.clj` (full trace at [refactor_error.txt](https://github.com/clojure-emacs/refactor-nrepl/files/63571/refactor_error.txt)).

This is using `refactor-nrepl 2.0.0-SNAPSHOT` with `clj-refactor 20151210.200`.

Cheers,

Matthew.

**Comment by expez** [comment]
Thanks for the report @scramjet!  I'll get a snapshot containing the fix published later today.

**Comment by scramjet** [comment]
Thanks!
