### ISSUE TITLE
Can't start REPL if clojars.org is down

### ISSUE THREAD

**Issue by julienfantin** [clojure-emacs/refactor-nrepl#136]
Clojars.org is down right now and I get this error when trying to launch a REPL:

```
error in process sentinel: nrepl-server-sentinel: Could not start nREPL server: Jan 01, 2016 5:47:33 PM org.apache.http.impl.execchain.RetryExec execute
INFO: I/O exception (java.net.NoRouteToHostException) caught when processing request to {s}->https://clojars.org:443: No route to host
```

I *assume* that an exception is thrown by `get-artifacts-from-clojars!` invoked from `artifact-list` and that a simple catch clause would solve this. Ironically I'm unable to verify this since I can't build the project due to Clojars being down!

**Comment by benedekfazekas** [comment]
thanks for the report. meanwhile you can work around this problem by setting `cljr-populate-artifact-cache-on-startup` to `nil` in your emacs config.
