### ISSUE TITLE
Cannot exclude clojure dependency

### ISSUE THREAD

**Issue by arrdem** [clojure-emacs/refactor-nrepl#140]
Since this plugin explicitly injects a dependency on Clojure 1.7, it's not possible for me to use this plugin while working on any of my Clojure 1.7+ forks. This is at least disappointing since it means I need to muck with my lein configs. Without disabling refactor-nrepl, your explicit Clojure 1.7 dep seems to win and my forks don't get loaded properly.

**Comment by expez** [comment]
Thanks for the report.

The middleware is now checking for the correct version on startup and warns otherwise so I think we can move the clojure dep into the `:provided` section with issue.

**Comment by benedekfazekas** [comment]
:+1: I guess this should go into the upcoming 2.0.0 too @expez

**Comment by arrdem** [comment]
Awesome. Thanks! Love this tool :smile:

**Comment by benedekfazekas** [comment]
thanks :) travis is still in slumber. so not yet published, might only happen tomorrow. if you can't wait you can always clone repo and run `./build.sh install`. Enjoy!

**Comment by benedekfazekas** [comment]
On clojars
