### ISSUE TITLE
lein plugin doesn't work when used outside the context of a project

### ISSUE THREAD

**Issue by wirion** [clojure-emacs/refactor-nrepl#141]
Hi,
I'm getting the following warning. But clojure 1.7.0 _is_ available and loaded.
```
Warning: refactor-nrepl requires org.clojure/clojure 1.7.0 or greater.
Warning: refactor-nrepl middleware won't be activated due to missing dependencies.
Warning: refactor-nrepl requires org.clojure/clojure 1.7.0 or greater.
Warning: refactor-nrepl middleware won't be activated due to missing dependencies.
nREPL server started on port 42016 on host 127.0.0.1 - nrepl://127.0.0.1:42016
REPL-y 0.3.7, nREPL 0.2.12
Clojure 1.7.0
OpenJDK 64-Bit Server VM 1.8.0_72-b15
    Docs: (doc function-name-here)
          (find-doc "part-of-name-here")
  Source: (source function-name-here)
 Javadoc: (javadoc java-object-or-class-here)
    Exit: Control+D or (exit) or (quit)
 Results: Stored in vars *1, *2, *3, an exception in *e
```
My ~/.lein/profiles.clj is:
```
{:user {:plugins [[cider/cider-nrepl "0.11.0-SNAPSHOT"]
                  [refactor-nrepl "2.0.0-SNAPSHOT"]                  
                  [quickie "0.3.6"]
                  [lein-pprint "1.1.2"]
                  [lein-try "0.4.3"]
                  [lein-figwheel "0.5.0-6"]
                  [com.jakemccrary/lein-test-refresh "0.10.0"]
                  [jonase/eastwood "0.2.1"]]
        :dependencies [[org.clojure/tools.nrepl "0.2.12"]
                       [org.clojure/tools.namespace "0.2.11"]]}}
```

**Comment by expez** [comment]
What does your `project.clj` look like?

**Comment by wirion** [comment]
Hi,
thanks for looking into this.
I got this by running `lein repl` outside of a project directory. I've checked inside projects, both with clojure 1.7.0 and 1.8.0 and it doesn't complain there.

**Comment by neverfox** [comment]
Yeah, this is strange because we're told that this can be put into our `~/.lein/profiles.clj` and there are all kinds of reasons you might be running lein outside of a project, e.g. to create the project. We shouldn't get an error when doing things like that.

**Comment by expez** [comment]
Proposed fix:

- [ ] Check `*clojure-version*` instead of reading the project map to remove warning out side project context.
- [ ] Update readme with recommendations that the user put this dep in the `:repl` profile instead.

**Comment by expez** [comment]
This is no longer a problem as the dependency is injected by the emacs frontend.

**Comment by randre03** [comment]
hello, I use vim for clojure (long story) so this happens to me. Suggestions on how to address (other than switching to emacs)?

**Comment by benedekfazekas** [comment]
not 100% sure about your situation but I suggest you could remove `refactor-nrepl` from your `profiles.clj` and add it to the projects `dev` profile where you want to use it.

As @expez says this is not a problem in emacs anymore as using `profiles.clj` is not recommended anymore.

also if I remember right you rather connect to an existing REPL process in the vim world than "jacking-in": you could also use leiningen's command line params to add `refactor-NREPL` when you launch it.

hope one of these helps.
