### ISSUE TITLE
Needless .cljc namespace reader macro usage

### ISSUE THREAD

**Issue by magnars** [clojure-emacs/refactor-nrepl#143]
I have a .cljc file with this ns:

```clojure
(ns example.foo
  (:require [example.bar :as bar]))
```

clean-ns turns this into:

```clojure
(ns example.foo
  #?@(:clj
       [(:require [example.bar :as bar])]
       :cljs
       [(:require [example.bar :as bar])]))
```

This seems needlessly verbose, as the form is the same in both cases.

**Comment by expez** [comment]
This should be easy to fix, just test if they are equal and pick one.
