### ISSUE TITLE
Connecting via Cider causes unending CPU intensive job

### ISSUE THREAD

**Issue by achesnais** [clojure-emacs/refactor-nrepl#150]
Hi,

I recently upgraded to version 2.2.0 and am experiencing the following:

Whenever I `cider-connect` to my repl, something somewhere starts computing intensively, using up an entire core.

I tried removing all my emacs packages and re-adding them one by one (after deleting the elpa folder of course), and can confirm the issue appeared when I added cljr-refactor.

I then tried connecting to the repl having enabled debug-mode. The CPU started spiking again, and remained high even after 2 minutes when the message "Artifact Cache Updated" appeared. 

One thing that I found weird is that the CPU spike is due to activity from 'main' according to the activity monitor, i.e. the Clojure code. So I profiled it with the JMC and found the issue actually lies in a bunch of calls to mranderson!

I see it's been upgraded recently – could this be the cause of the problem?

**Comment by benedekfazekas** [comment]
mranderson is just a tool inlineing our dependencies so they can't clash with the project's dependencies, so this is a redhering. as discussed on slack it is most likely the macro occurrence cache being loaded. could be interesting what your stack shows

**Comment by expez** [comment]
Is it literally unending or does it finish (after an unreasonably long time)?

You can turn off caching by toggling various settings for clj-refactor, but the work will be done synchronously instead when you request e.g. clojars artifacts or AST-based refactorings.

@benedekfazekas is seeing a lot of CPU usages himself, but everything is working perfectly for me.  Even on a 20kloc project at work the eager building of ASTs finishes within a minute or two and CPU usages goes down to nothing.

**Comment by bstiles** [comment]
Additional data point. I experienced this problem, also. My codebase is less than 7,000 lines, though there are a lot of dependencies on the classpath, if that matters. I tried various permutations of fewer dependencies and removed code from my codebase (based on speculation, not rigorous examination) to see if I could pin the problem to a particular namespace. Nothing helped. I never saw the CPU go down, though I can't commit to having paid close enough attention on runs longer than several minutes.

**Comment by jarohen** [comment]
Same here - have just done a thread dump, here's the offending thread's stack trace: https://gist.github.com/jarohen/341a380cbfae7c5a203e

HTH?

**Comment by expez** [comment]
@jarohen thanks, that's very helpful.  That narrows it down to the macro occurrence cache.

A temporary workaround is to do `(setq cljr-eagerly-cache-macro-occurrences-on-startup nil)`.  It's likely that this code path will trigger once you start using `cljr-find-symbol`, though.

**Comment by benedekfazekas** [comment]
@achesnais @bstiles @jarohen there is a new 2.2.0-SNAPSHOT on clojars hopefully fixing this. pls retest with your projects and let me know your findings.

**Comment by expez** [comment]
Unfortunately that didn't solve it.  I'm seeing this too now.

**Comment by expez** [comment]
Ok, what happens here is that the warm-macro-occurrences-cache function you wrote does the following @benedekfazekas: 

1. For each ns in the project
2. Get all that ns's dependencies 
3. For each dependency (including those in third party libs)
  5. Look for macros in that ns
  6. Look for occurrences of those macros in all project files

There's also no memoization / caching so all namespaces are processed multiple times.

So there's no infinite loop, it's just processing thousands and thousands of files needlessly.

I'm disabling the caching in both packages until one of us has time to rewrite this function.

**Comment by expez** [comment]
New snapshot is out with this temp fix

**Comment by benedekfazekas** [comment]
cheers for the snapshot. will have a look

**Comment by benedekfazekas** [comment]
@expez 

> 3/ii Look for occurrences of those macros in all project files

I think this statement is wrong. It rather

`Looks for occurrences of those macros in the given ns`

I may be missing something so pls point me to the line where it searches all project files for macros of a dependency.

**Comment by expez** [comment]
You may be right. The relevant part is that it does work for third party libs.  All that work can be skipped.

**Comment by benedekfazekas** [comment]
> The relevant part is that it does work for third party libs. All that work can be skipped.

not sure about this. I want to be able to find occurrences of third party macros as well. For `replace-refer-all` for sure but I guess it might be necessary for `find-usages` (you can easily search for a third party macro there too)
