### ISSUE TITLE
"Adding missing libspec" doesn't find symbols in not ":require"-d namespaces

### ISSUE THREAD

**Issue by mrroman** [clojure-emacs/refactor-nrepl#152]
1. Create project `lein new app project`.
2. Add some dependency (e.g. aleph "0.4.1-beta5").
3. Go to core.clj file and run cider-jack-in.
4. Write (http/websocket-client) and invoke cljr-add-missing-libspec.
5. It doesn't find symbol in other namespaces.

I have installed:
- refactor-nrepl-2.2.0-20160309.115504-8.jar
- cider-20160309.808
- clj-refactor-20160303.536

**Comment by malchmih** [comment]
Actually noticed this long time ago, just wasn't a big issue for me.

**Comment by expez** [comment]
We query the REPL for information about namespaces and symbols, which is why this doesn't work as you'd like.

This was brought up before and the solution is to load every file on the classpath into the running process.  I don't know if that's a good idea or not.

**Comment by mrroman** [comment]
Current behavior makes the functionality really bounded. Maybe it would be possible to have a cache for symbols that are defined in non-snapshot jars.

**Comment by expez** [comment]
> Current behavior makes the functionality really bounded. 

I don't really agree.  Using the reloaded workflow and working on an existing app 99% of the symbols I try to require/import are found.  I had completely forgotten about this problem.

> Maybe it would be possible to have a cache for symbols that are defined in non-snapshot jars.

Yes, as I said that would be entirely possible, but I'm not sure at what cost this would come at.

**Comment by expez** [comment]
My guess is that the fix will be unusable on larger projects.  Furthermore, some namespaces are side-effecting on load, and will cause bugs that are super hard to track dow.  This means the feature would have to be opt-in and we'd have to implemented a blacklist so users could opt out of requiring certain namespaces.

I'm thinking it's time to close this issue, as nobody seems interested in working on this.  @benedekfazekas What do you think?

**Comment by benedekfazekas** [comment]
I would not decline a such a patch straight away. But although not closely related I am thinking to give a go to analyze only loaded nses (as ppl tend to use some flavour of reloaded workflow anyway). So I would say current behaviour is probably good enough for most use cases and in line with my future intentions.

Again if somebody is happy to play with a patch and submit it, that is good but happy with this closed.
