### ISSUE TITLE
Always have to call `add-missing-libspec` twice

### ISSUE THREAD

**Issue by tdavis** [clojure-emacs/refactor-nrepl#155]
The first time I call `cljr-add-missing-libspec` I don't get an error, my namespace declaration is organized, but the library itself is not added. I then have to save the buffer and call the method again, after which the library is present.

**Comment by expez** [comment]
Thanks for the report.  This is a a known bug,  and should be fixed in 2.0.0-snapshot.

**Comment by tdavis** [comment]
Sorry for the delay, updating to the snapshot fixed it. Thanks!
