### ISSUE TITLE
Documentation?

### ISSUE THREAD

**Issue by mauricioszabo** [clojure-emacs/refactor-nrepl#162]
Is there any documentation of using this middleware in an editor-agnostic way? The examples on the README are outdated, and I couldn't found any way of making it work properly with the REPL alone.

**Comment by expez** [comment]
All messages are handled [here](https://github.com/clojure-emacs/refactor-nrepl/blob/master/src/refactor_nrepl/middleware.clj).

If you want to call stuff directly from the repl you can call the functions the middleware handler delegates to.

e.g. to call [clean-ns](https://github.com/clojure-emacs/refactor-nrepl/blob/master/src/refactor_nrepl/ns/clean_ns.clj#L38) you'd do:

`(clean-ns {:path "/home/expez/awesome-project/src/clojure_file.clj"})`.

The various `ops` which are handled by our middleware can also be inspected in the [middleware ns](https://github.com/clojure-emacs/refactor-nrepl/blob/master/src/refactor_nrepl/middleware.clj) if the README is inadequate.

I'll take a pass at updating the readme, it is indeed slightly misleading (e.g. the client is only used for integration tests now).  It's perhaps also a bit too terse.  I frequently use it as a reference myself, though, so it isn't entirely useless :p 

Any pointers about what to add / fix would be helpful.

**Comment by mauricioszabo** [comment]
I'm sorry, but I still don't understand how to work with this library. I changed some calls to the new namespaces, but I'm getting strange errors:

```clojure
user=> (refactor-nrepl.find.find-symbol/find-symbol {:ns 'backend.db-api :symbol "login-user"})
NullPointerException   java.util.regex.Matcher.getTextLength (Matcher.java:1283)

user=> (refactor-nrepl.find.find-symbol/find-symbol {:file "/home/mauricio/projetos/yendy/backend/src/backend/db_api.clj", :dir "/home/mauricio/projetos/yendy/backend/" :ns 'backend.db-api :symbol "login-user", :line 10, :column 7})
NullPointerException   java.util.regex.Matcher.getTextLength (Matcher.java:1283)

user=> (refactor-nrepl.ns.resolve-missing/resolve-missing 'list-objs)
IllegalArgumentException Invalid input to resolve missing: ''  refactor-nrepl.ns.resolve-missing/resolve-missing (resolve_missing.clj:60)
```

Furthermore, `rename-symbol` doesn't exist in any namespace, and `refactor-nrepl.client` it's on the test directory....

**Comment by expez** [comment]
Sorry for dropping the ball on this @mauricioszabo, but I've been extremely busy lately :( 

I've updated the readme and removed the confusing references client namespace, which we now only use for our integration tests.

I've also added a new toplevel section about [passing message to and from refactor-nrepl](https://github.com/clojure-emacs/refactor-nrepl#passing-messages-to-and-from-refactor-nrepl).

Hopefully that addresses some of your questions.  If you need any further help in getting started you should join us on [gitter](https://gitter.im/clojure-emacs/refactor-nrepl) where we can chat and get you some real-time assistance.
