### ISSUE TITLE
Projects without clojure dependency cannot load clj-refactor middleware

### ISSUE THREAD

**Issue by aengelberg** [clojure-emacs/refactor-nrepl#163]
## Expected behavior

In a Leiningen project with no `[org.clojure/clojure "xxx"]` dependency specified (which defaults to 1.8.0 on the latest version of Leiningen), cider-jack-in should load and function as usual.
## Actual behavior

REPL starts, but with the following warning.

```
error in process sentinel: nrepl-server-sentinel: Could not start nREPL server: Warning: refactor-nrepl requires org.clojure/clojure 1.7.0 or greater.
Warning: refactor-nrepl middleware won't be activated due to missing dependencies.
```
## Steps to reproduce the problem

Remove or comment out `[org.clojure/clojure "1.8.0"]` in a new leiningen project.
### clj-refactor.el and refactor-nrepl version information

clj-refactor and refactor-nrepl `2.2.0`
### CIDER version information

Cider 0.12.0
### Leiningen or Boot version

Leiningen 2.6.1
### Emacs version

24.5.1
### Operating system

OS X 10.11.3 El Capitan

**Comment by raxod502** [comment]
I encounter this warning message when running `cider-jack-in` outside the context of a project. It seems to be new (I haven't done much Clojure development over the last month or two, but between then and now this warning has started to appear without any changes to my configuration).
