### ISSUE TITLE
Rename file doesn't properly rename classes created by defrecords

### ISSUE THREAD

**Issue by expez** [clojure-emacs/refactor-nrepl#172]
In one of my schemas I had a check like `(partial instance? foo.bar.Baz)` to verify that I had a record of a given type.  When I moved `foo/bar.clj` to `foo/bar/qux.clj` I expected the check to be fixed to `(partial instance? foo.bar.qux.Baz)`.

**Comment by MalloZup** [comment]
autogenerated with https://github.com/MalloZup/doghub:  issue inactive since 450 days. Please update the issue or close it
