### ISSUE TITLE
Erroneous warnings about Clojure version on cider-jack-in without project

### ISSUE THREAD

**Issue by raxod502** [clojure-emacs/refactor-nrepl#177]
> Relocated from clojure-emacs/cider-nrepl#384.

## Expected behavior

`M-x cider-jack-in` should work correctly outside of a Clojure project, as well as inside one.

## Actual behavior

When not inside a Clojure project, the REPL still starts but warnings from `refactor-nrepl` are printed to `*nrepl-server*`. See below.

## Steps to reproduce the problem

Make sure you are **not** inside a Clojure project. The error does not occur when inside a project.

```
emacs -Q
M-x package-initialize RET
M-x cider-jack-in RET y
C-x b *nrepl-server* RET
```

Contents of buffer:

```
Warning: refactor-nrepl requires org.clojure/clojure 1.7.0 or greater.
Warning: refactor-nrepl middleware won't be activated due to missing dependencies.
Warning: refactor-nrepl requires org.clojure/clojure 1.7.0 or greater.
Warning: refactor-nrepl middleware won't be activated due to missing dependencies.
Warning: refactor-nrepl requires org.clojure/clojure 1.7.0 or greater.
Warning: refactor-nrepl middleware won't be activated due to missing dependencies.
nREPL server started on port 49162 on host 127.0.0.1 - nrepl://127.0.0.1:49162
```

## Workaround

The following resolves the error:

```
(setq cider-jack-in-auto-inject-clojure 'latest)
```

### clj-refactor.el and refactor-nrepl version information

```
clj-refactor 2.3.0-SNAPSHOT (package: 20161127.1306), refactor-nrepl 2.3.0-SNAPSHOT
```

### CIDER version information

```
;; CIDER 0.15.0snapshot (package: 20161211.101125), nREPL 0.2.12
;; Clojure 1.8.0, Java 1.8.0_31
```

### Leiningen or Boot version

```
Leiningen 2.7.1 on Java 1.8.0_31 Java HotSpot(TM) 64-Bit Server VM
```

### Emacs version

```
GNU Emacs 25.1.1 (x86_64-apple-darwin13.4.0, NS appkit-1265.21 Version 10.9.5 (Build 13F1911)) of 2016-09-20
```

### Operating system

```
El Capitan 10.11.6
```

### Additional info

* All Emacs packages are installed from MELPA.
* I have deleted my `profiles.clj`.
* Here is the command run when I `M-x cider-jack-in`:

  ```
  Starting nREPL server via /usr/local/bin/lein update-in :dependencies conj \[org.clojure/tools.nrepl\ \"0.2.12\"\ \:exclusions\ \[org.clojure/clojure\]\] -- update-in :plugins conj \[refactor-nrepl\ \"2.3.0-SNAPSHOT\"\] -- update-in :plugins conj \[cider/cider-nrepl\ \"0.15.0-SNAPSHOT\"\] -- repl :headless...
  ```

* Here is the complete output after I have wiped my `~/.m2` and `~/.lein`:

  ```
  Retrieving refactor-nrepl/refactor-nrepl/2.3.0-SNAPSHOT/refactor-nrepl-2.3.0-20160812.065303-6.pom from clojars
  Retrieving org/clojure/tools.nrepl/0.2.12/tools.nrepl-0.2.12.pom from central
  Retrieving org/clojure/pom.contrib/0.1.2/pom.contrib-0.1.2.pom from central
  Retrieving org/sonatype/oss/oss-parent/7/oss-parent-7.pom from central
  Retrieving org/clojure/clojure/1.2.0/clojure-1.2.0.pom from central
  Retrieving refactor-nrepl/refactor-nrepl/2.3.0-SNAPSHOT/refactor-nrepl-2.3.0-20160812.065303-6.jar from clojars
  Retrieving org/clojure/tools.nrepl/0.2.12/tools.nrepl-0.2.12.jar from central
  Retrieving org/clojure/clojure/1.2.0/clojure-1.2.0.jar from central
  Warning: refactor-nrepl requires org.clojure/clojure 1.7.0 or greater.
  Warning: refactor-nrepl middleware won't be activated due to missing dependencies.
  Retrieving cider/cider-nrepl/0.15.0-SNAPSHOT/cider-nrepl-0.15.0-20161210.103803-3.pom from clojars
  Retrieving org/tcrawley/dynapath/0.2.5/dynapath-0.2.5.pom from central
  Retrieving cider/cider-nrepl/0.15.0-SNAPSHOT/cider-nrepl-0.15.0-20161210.103803-3.jar from clojars
  Retrieving org/tcrawley/dynapath/0.2.5/dynapath-0.2.5.jar from central
  Warning: refactor-nrepl requires org.clojure/clojure 1.7.0 or greater.
  Warning: refactor-nrepl middleware won't be activated due to missing dependencies.
  Warning: refactor-nrepl requires org.clojure/clojure 1.7.0 or greater.
  Warning: refactor-nrepl middleware won't be activated due to missing dependencies.
  Retrieving clojure-complete/clojure-complete/0.2.4/clojure-complete-0.2.4.pom from clojars
  Retrieving org/clojure/clojure/1.8.0/clojure-1.8.0.pom from central
  Retrieving org/clojure/clojure/1.8.0/clojure-1.8.0.jar from central
  Retrieving clojure-complete/clojure-complete/0.2.4/clojure-complete-0.2.4.jar from clojars
  nREPL server started on port 63403 on host 127.0.0.1 - nrepl://127.0.0.1:63403
  ```
  ```
  ;; Connected to nREPL server - nrepl://localhost:63403
  ;; CIDER 0.15.0snapshot (package: 20161211.101125), nREPL 0.2.12
  ;; Clojure 1.8.0, Java 1.8.0_31
  ;;     Docs: (doc function-name)
  ;;           (find-doc part-of-name)
  ;;   Source: (source function-name)
  ;;  Javadoc: (javadoc java-object-or-class)
  ;;     Exit: <C-c C-q>
  ;;  Results: Stored in vars *1, *2, *3, an exception in *e;
  ;; ======================================================================
  < welcome message omitted >
  ;; ======================================================================
  user> 
  ```

**Comment by raxod502** [comment]
I would add that there shouldn't be any warning generated in the case that we're outside a project, or there should be an option in CIDER to prevent it (perhaps by not injecting `clj-refactor` outside a project).

**Comment by expez** [comment]
How would users learn that refactor-nrepl, and therefore the most advanced refactorings, only work in the context of a project unless we give a warning?

Without the warning I fear users would be surprised they can't refactor and then open issues asking why.

**Comment by raxod502** [comment]
Oh, I didn't realize that the project was required. In that case, I think there should be an option to disable the warning, although that option can be disabled by default.

The issue is that CIDER automatically injects `refactor-nrepl` when you `cider-jack-in`, so by default users will get a warning every time they open a REPL for anything, even if they are unaware even of the existence of `refactor-nrepl`.

**Comment by expez** [comment]
@raxod502 cider doesn't do that, clj-refactor does it.  You can disable that by putting 

```el
(setq cljr-inject-dependencies-at-jack-in nil)
```

In your `.emacs`.

Alternatively you can do this:

```el
(defun no-project-hook ()
  (unless (cljr--project-dir)
    (setq-local cljr-inject-dependencies-at-jack-in nil)))

(add-hook 'clojure-mode-hook #'no-project-hook)
```

Which would only set that variable in `.clj` buffers which aren't associated with a project.

We can't set a variable because the variables live in Emacs (where they are easily editable). They can only by sent to the middleware once it's started (along with the REPL), but the warning happens during startup.

**Comment by raxod502** [comment]
I see, so this is really (at least partially) an issue with `clj-refactor`? (That is, it should not be injecting `refactor-nrepl` outside of a project?)

Thanks for the suggestion. I will add this to my init-file in the mean-time.

**Comment by raxod502** [comment]
FYI: `clj-refactor` mutates CIDER's injections globally in an autoload, so the following is necessary to override its behavior properly:

```
(setq cljr-inject-dependencies-at-jack-in nil)
(defun no-project-hook
  (when (cljr--project-dir)
        (make-local-variable 'cider-jack-in-lein-plugins)
        (make-local-variable 'cider-jack-in-nrepl-middlewares)
        (cljr--inject-jack-in-dependencies)))
(add-hook 'clojure-mode-hook #'no-project-hook)
```

**Comment by expez** [comment]
Fixed in https://github.com/clojure-emacs/clj-refactor.el/commit/ebabe3b433163e6ce4ee53c845b6c195d57251a0

and https://github.com/clojure-emacs/refactor-nrepl/commit/509769a63d1336b7c4fbb6bdbaf9015ecde35e24
