### ISSUE TITLE
refactor-nrepl interferes with existing working web app

### ISSUE THREAD

**Issue by hellofunk** [clojure-emacs/refactor-nrepl#18]
I thought you might like to see this issue:

https://github.com/dakrone/clj-http/issues/249

I had this in my lein plugins:

`:plugins [[refactor-nrepl "0.3.0-SNAPSHOT"]]`

As soon as I removed it, the Java error disappeared and my app started working again. I was not actually using the refactor tools when the crash happens.

I'd like to keep using the refactor functionality, so if you have advice on what might have cause this, I'm all ears.

**Comment by bbatsov** [comment]
Most likely - a dependency conflict.

**Comment by hellofunk** [comment]
Resolving the conflict is proving to be no small chore.

**Comment by benedekfazekas** [comment]
yeah I think so. I think it is related to pomegranate which depends on wagon-http which depends on an older version of `org.apache.httpcomponents` than `clj-http`

we use [mranderson](https://github.com/benedekfazekas/mranderson) to minimise these conflicts. but this guy is basically a bunch of java classes: mranderson serves no remedies for those...

I think we had a chat with @expez at some point to try to get rid of pomegranate for this reason: but not easy if we want to have resolve artifacts...

**Comment by benedekfazekas** [comment]
you can try to explicitly define the higher httpcomponents version in your project's project.clj and see if that solves the problem...

**Comment by benedekfazekas** [comment]
alternatively we could manually inline httpcomponents (and wagon http, pomegranate?!) as java source. sounds horrible but doable... @expez what do you think?

**Comment by hellofunk** [comment]
I am definitely not going to reorganize my own working project code just so I can use refactor tools in an editor.

**Comment by benedekfazekas** [comment]
fair point @hellofunk

**Comment by expez** [comment]
@benedekfazekas I don't see any other option than inlining

**Comment by benedekfazekas** [comment]
we might get away with inlining just a few java classes which are really used by hotload... don't know. really guessing around here...

**Comment by expez** [comment]
are [boot's pods](https://github.com/boot-clj/boot/wiki/Pods) the solution to this and all similar problems?  If I'm reading this right we could put `refactor-nrepl` in its own pod and do away with mranderson?

**Comment by bbatsov** [comment]
I think they might be! I'm thinking of using them for cider-nrepl itself.

On 22 January 2015 at 15:47, Lars Andersen <notifications@github.com> wrote:

> are boot's pods <https://github.com/boot-clj/boot/wiki/Pods> the solution
> to this and all similar problems? If I'm reading this right we could put
> refactor-nrepl in its own pod and do away with mranderson?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/clojure-emacs/refactor-nrepl/issues/18#issuecomment-71022005>
> .
>



-- 
Best Regards,
Bozhidar Batsov

http://www.batsov.com

**Comment by benedekfazekas** [comment]
this looks really cool. what i don't really get after the first read if we can produce a standalone jar with pods. in other words would that mean that the middleware users have to use pods themselves? I guess not...

**Comment by benedekfazekas** [comment]
so @expez I suppose we want to put `refactor-nrepl`'s dependencies into pods.

**Comment by benedekfazekas** [comment]
@hellofunk could you pls retest with latest 0.3.0-SNAPSHOT (just adding back the `[refactor-nrepl "0.3.0-SNAPSHOT"]` to your plugins in your `profiles.clj` should do it)

**Comment by expez** [comment]
@benedekfazekas I tried looking at [lein-capsule](https://github.com/circlespainter/lein-capsule) on friday but `lein capsule` just failed on me.  I've opened an issue with the repo.  The capsule project looks promising to me.

**Comment by benedekfazekas** [comment]
@expez looks cool too. i did not give up on boot either only hopefully the above simple fix solves hellofunk's (and other clj-http user's) problems. both boot and/or capsule makes sense still

**Comment by stoeckley** [comment]
Looks like this is working. I added it back to my .lein/profiles.clj and launched the app without error and started a server. I also used the "find usages" feature of clj-refactor, which requires the refactor-nrepl support, and it worked fine. Great!

**Comment by hellofunk** [comment]
Sorry, posted from a dummy account I rarely use. Looks like this is working. I added it back to my .lein/profiles.clj and launched the app without error and started a server. I also used the "find usages" feature of clj-refactor, which requires the refactor-nrepl support, and it worked fine. Great

**Comment by benedekfazekas** [comment]
cool. I close this then and open an other one for ourselves to look into pods and/or capsules

**Comment by nwolfe** [comment]
Spent a lot of time tracking down this issue - :+1: :+1: :+1: for fixing these dependency conflicts in a more robust way as to not interfere with other Clojure projects.
