### ISSUE TITLE
`namespace-aliases` breaks with bencode as serialization format

### ISSUE THREAD

**Issue by hkupty** [clojure-emacs/refactor-nrepl#180]
## Expected behavior
Requesting `namespace-aliases` with `bencode` as `serialization-format` returns as expected.

## Actual behavior
Passing `bencode` as a `serialization-format` option causes the `refactor-nrepl` to break while trying to convert the symbols to string with the following error:
`java.lang.ClassCastException: clojure.lang.Symbol cannot be cast to java.lang.String`

The exception above is caught when stopping the repl after requesting the aliases.

## Steps to reproduce the problem
Request `namespace-aliases` with `serialization-format` equals to `bencode`

## Environment & Version information
Neovim nrepl library [hkupty/acid.nvim](http://github.com/hkupty/acid.nvim), `testing` branch.
Clojre version 1.8

### clj-refactor.el and refactor-nrepl version information
No clj-refactor.el
`[refactor-nrepl "2.2.0"]`

### CIDER version information
No CIDER

### Leiningen or Boot version
`Leiningen 2.7.0 on Java 1.8.0_112 OpenJDK 64-Bit Server VM`

### Emacs version
No Emacs

### Operating system
Arch Linux, 4.8.13-1-ARCH

**Comment by expez** [comment]
Hi

I'm not sure what happens here.  It would be helpful if you could provide the message being sent to the middleware, so we can figure out where the ClassCastException happens.

**Comment by expez** [comment]
I'm also noticing that `serialize-reply`, which gives the bencode option, isn't being used everywhere it should.  

This feature isn't used by the emacs client, so we haven't noticed.  Sorry about that.

**Comment by hkupty** [comment]
Thanks for promplty answering.

I'm sending a simple message, like this:
``` clojure
{"serialization-format" "bencode"
 "op"                   "namespace-aliases"}
```

Nothing really special going on here. If I send it without providing the `serialization-format` parameter, it works as it should, but it is substantially harder for me to parse that, since I'd have to read from edn to python, which is the host language (for integrating with neovim).

**Comment by expez** [comment]
This is my guess as to what goes wrong here:

`namespace-aliases` returns a bunch of symbols and since bencode doesn't have symbols, only strings, `tools.nrepl`blows up on the conversion?

If that's the cause, then we can certainly walk the data and do manual conversion to the types supported by bencode, but isn't that the job of nrepl?

**Comment by hkupty** [comment]
That looks certainly like it.

Not sure that it should be fixed on `clojure.nrepl`, though. Probably won't hurt opening an issue for them.
Either way, the solution would be to serialize symbols to string.

**Comment by expez** [comment]
I'll get a snapshot out fixing this tomorrow.  Even if this is a problem with nrepl I don't want to leave you hanging for months while it gets addressed.

**Comment by hkupty** [comment]
Thanks for the attention!

**Comment by expez** [comment]
A new snapshot is available if you want to give this fix a spin @hkupty.

**Comment by hkupty** [comment]
I just tested and it returned me an error with `'Wrong number of args (1) passed to: walk/postwalk'`

**Comment by hkupty** [comment]
Looks like it's missing `data` before the last parens here: https://github.com/clojure-emacs/refactor-nrepl/blob/eb338bf3f6f37871465a3c073ec1847c855d1776/src/refactor_nrepl/middleware.clj#L60

**Comment by expez** [comment]
Shit, so sorry about that.  Fixed it in steps while running integration tests at work :p 

I've deployed another snapshot.  

Happy holidays!

**Comment by hkupty** [comment]
Sorry for taking long to answer. It worked perfectly! Thanks for the support!

Happy holidays!

**Comment by expez** [comment]
Let us know if there's anything else we can do to help your use case, @hkupty.  @benedekfazekas and I are always very excited when another frontend shows interest!
