### ISSUE TITLE
cljr-rename symbol gives "refactor-nrepl is unable to build an AST

### ISSUE THREAD

**Issue by biancazzurri** [clojure-emacs/refactor-nrepl#182]
## Expected behavior
cljr-rename-symbol should proceed to renaming a symbol

## Actual behavior
an error is given:
refactor-nrepl is unable to build an AST for <namespace>. tool.analyzer encountered the following problem: Unable to resolve classname: Date

## Steps to reproduce the problem
create an empty project, in some file:
(ns nmspc
  (:import java.util.Date))

(def a (Date.))

(def func [] nil)

M-x cljr-rename-symbol, press y

When Date. is not used the problem is gone
### clj-refactor.el and refactor-nrepl version information
clj-refactor: 2.3.0 
refactor-nrepl: 2.3.0

*You can call `cljr-version` to obtain this information.*

### CIDER version information

CIDER 0.15.0snapshot
Clojure 1.8.0, Java 1.8.0_31

**Comment by expez** [comment]
The code you pasted is invalid, and you didn't specify what you tried to rename.  I tried renaming the final occurrence of `func` in this, slightly modified code, and it works fine:

```clj
(ns test.core
  (:import java.util.Date))

(def a (Date.))

(defn func [] nil)

(func)
```

**Comment by biancazzurri** [comment]
In my case I am not given the opportunity to give the name of the variable to rename, the error occurs before that

**Comment by benedekfazekas** [comment]
I tried to rename `a` def as well, worked. as @expez points out this

`(def func [] nil)` is invalid. Fix it and try again.
