### ISSUE TITLE
cygwin filepath support

### ISSUE THREAD

**Issue by tsulej** [clojure-emacs/refactor-nrepl#183]
Can't invoke commands which requires file load on the refactor-nrepl side. For example `rename symbol`.

After some debugging I found that problem is similar to this issue: [https://github.com/clojure-emacs/cider/pull/735](https://github.com/clojure-emacs/cider/pull/735)
And instead of simply `slurp` filename should be treated by `cygpath` before.

## Actual behavior

Calling `rename symbol` causes following exception:

> cljr--get-error-value: Error in nrepl-refactor: java.io.FileNotFoundException:
> \home\tsulej\clojure2d\src\clojure2d\color.clj (System nie może odnaleźć określonej ścieżki <--- can't find path) 
> at java.io.FileInputStream.open0 (:-2)
>    java.io.FileInputStream.open (:-1)
>    java.io.FileInputStream.<init> (:-1)
>    clojure.java.io$fn__9520.invokeStatic (io.clj:229)
>    clojure.java.io/fn (io.clj:229)
> [...]

nrepl debug shows such messages:

> (--> 
>   op  "info"
>   session  "ad551abf-8b65-4915-b863-3294ba49434d"
>   ns  "clojure2d.color"
>   symbol  "get-luma3"
>   id  "17"
> )
> (<-- 
>   arglists-str  "([c])"
>   column  1
>   doc  "get luma from color"
>   file  "file:/C:/cygwin64/home/tsulej/clojure2d/src/clojure2d/color...."
>   id  "17"
>   line  31
>   name  "get-luma3"
>   ns  "clojure2d.color"
>   session  "ad551abf-8b65-4915-b863-3294ba49434d"
>   status  ("done")
> )
> (--> 
>   op  "find-symbol"
>   prefix-rewriting  "true"
>   debug  "false"
>   ns  "clojure2d.color"
>   dir  "/home/tsulej/clojure2d/"
>   file  "/home/tsulej/clojure2d/src/clojure2d/color.clj"
>   line  31
>   column  14
>   name  "get-luma3"
>   ignore-errors  nil
>   session  "ad551abf-8b65-4915-b863-3294ba49434d"
>   id  "18"
> )
> (<-- 
>   err  "java.io.FileNotFoundException: \home\tsulej\clojure2d\src\cl..."
>   ex  "class java.io.FileNotFoundException"
>   id  "18"
>   session  "ad551abf-8b65-4915-b863-3294ba49434d"
>   status  ("done" "refactor-nrepl-error")
> )

## Steps to reproduce the problem

Under Cygwin I run `startxwin` to run X Window System and run Emacs, open file, invoke `cider-jack-in` or connect to extrenally run REPL. `C-c RET r s` causes error.

### clj-refactor.el and refactor-nrepl version information

clj-refactor 2.3.0-SNAPSHOT (package: 20161223.1457), refactor-nrepl 2.3.0-SNAPSHOT

### CIDER version information

```
;; Connected to nREPL server - nrepl://localhost:63103
;; CIDER 0.15.0snapshot (package: 20170104.1330), nREPL 0.2.12
;; Clojure 1.8.0, Java 1.8.0_91
```

### Leiningen or Boot version

Leiningen 2.7.1 on Java 1.8.0_91 Java HotSpot(TM) 64-Bit Server VM

### Emacs version

GNU Emacs 25.1.1 (x86_64-unknown-cygwin, GTK+ Version 3.18.9) of 2016-09-17

### Operating system

Windows 10, 
CYGWIN_NT-10.0 Dell 2.6.1(0.305/5/3) 2016-12-16 11:55 x86_64 Cygwin

**Comment by benedekfazekas** [comment]
we should use what is already in cider from clj-refactor I suppose

**Comment by tsulej** [comment]
I see that I mistakenly assigned bug here. Bug should go to the emacs side (clj-refactor). Emacs under Cygwin has native converting functions. [Info](https://www.gnu.org/software/emacs/manual/html_node/elisp/File-Names.html#DOCF13).
I'll try to make some tests.

**Comment by expez** [comment]
Move it if you want, but we're kind of used to closing issues across these two repos so it's not really a problem @tsulej.

**Comment by tsulej** [comment]
Created pull request: https://github.com/clojure-emacs/clj-refactor.el/pull/357
