### ISSUE TITLE
Promote Function functionality

### ISSUE THREAD

**Issue by hellofunk** [clojure-emacs/refactor-nrepl#19]
I'm trying to use this feature:

`pf: promote function literal or fn, or fn to defn`

Either I don't understand it, or it is not doing what it should be.

If I have this:

`#(println "hello")`

Shouldn't the `pf` change it to this:

`(fn [] (println "hello"))`

And if I then did it again, it would do this:

`(defn ??? [] (println "hello"))`

For me, all it does is report this:

`Can't find definition of anonymous function!`

**Comment by benedekfazekas** [comment]
i am not sure it makes sense to define an anonymous fn without at least one param, does it? I suppose promote fn expects `%\d*` in the anon fn...

**Comment by hellofunk** [comment]
I get the same behavior with something like this:

`#(println %)

Produces the same `Can't find...` response in the mini-buffer.

**Comment by expez** [comment]
This is now fixed in master.

There was an edge case when a function literal appeared as a toplevel form.  This should never happen in actual code, but it still makes sense to fix this as someone might test the feature and be confused about why it isn't working.

Thanks for the report @hellofunk!
