### ISSUE TITLE
Dependency on cider-nrepl is not declared in project.clj

### ISSUE THREAD

**Issue by technomancy** [clojure-emacs/refactor-nrepl#199]
This project has a dependency on `cider/cider-nrepl` that is documented in the readme but not declared as a dependency in `project.clj`.

**Comment by benedekfazekas** [comment]
not sure what you mean. dependency on `cider/cider-nrepl` is declared in the `project.clj` as a provided dependency: https://github.com/clojure-emacs/refactor-nrepl/blob/master/project.clj#L22. do you think this is a bad idea?

**Comment by technomancy** [comment]
The provided profile is intended for situations where the dependency is
going to be run in a framework where that is known to already be present.

That's not really the case here if the user is required to manually add
it in. Maybe there's something I'm missing here, but I don't see the
point in requiring the user to declare the dependency when you could
just declare it normally and have it just work.

**Comment by benedekfazekas** [comment]
this is a fair point.

however, this is a kinda special case here. both this project and `cider-nrepl` are implemented as `nrepl` middlewares. this project's primary client [clj-refactor.el](/clojure-emacs/clj-refactor.el) is explicitly dependent on cider (the respective client of `cider-nrepl`) and
- checks if cider-nrepl is available on the nrepl server it is connected to (see https://github.com/clojure-emacs/clj-refactor.el/blob/master/clj-refactor.el#L879-L886),
- both cider (the elisp client of `cider-nrepl`) and `clj-refactor.el` autoinject their dependencies when you jack-in to a REPL in Emacs.

in other words, this project is part of some kind of framework (tooling implemented as nrepl middlewares), where we can safely assume that `cider-nrepl` is present.

there was also a discussion around this quite a while ago as far as i remember. eg. if we should add cider as a proper dependency, inline it or declare it as provided. don't quite remember the details, i can try to dig them out from the closed github issues but currently `clj-refactor` and its backend `refactor-nrepl` is practically a cider plugin. users don't really need to manually add `cider-nrepl` as dependency themselves.

sidenote: as far as i am aware both `refactor-nrepl` and `cider-nrepl` are used in tooling support for other editors as well (vim, lighttable etc): not really sure how these dependencies are handled there but it is not likely that the users need to wire together these middlewares themselves.

hope this makes sense, sorry for the kinda long answer, did not have time to properly shorten it ;)

**Comment by technomancy** [comment]
I see. If it's not intended to be used from outside cider then maybe the
provided scope makes sense; I didn't realize that was the case from the readme.

**Comment by benedekfazekas** [comment]
no worries. I guess it would make sense to make this more explicit in the README.
