### ISSUE TITLE
cljr-clean-ns does not work with CIDER 0.15

### ISSUE THREAD

**Issue by scramjet** [clojure-emacs/refactor-nrepl#204]
## Expected behavior

Clean ns works

## Actual behavior

Fails with: cljr-clean-ns: Wrong number of arguments: (0 . 0), 1

## Steps to reproduce the problem

Run cljr-clean-ns (2.3.1) with CIDER 0.15

### clj-refactor.el and refactor-nrepl version information

2.3.1 for both

### CIDER version information

CIDER 0.15.0

### Emacs version

Emacs 25.2.1

### Operating system

MacOS 10.12.5

# Fix

It appears cider-eval-ns-form has changed and lost its single parameter. A quick hack to cljr as below appears to fix the issue for me:

```
(defun cljr-clean-ns ()
  "Clean the ns form for the current buffer.

See: https://github.com/clojure-emacs/clj-refactor.el/wiki/cljr-clean-ns"
  (interactive)
  (cljr--ensure-op-supported "clean-ns")
  ;;(cider-eval-ns-form :sync)
  (cider-eval-ns-form)
  (cljr--clean-ns))```

**Comment by expez** [comment]
Thanks.  This was fixed on master a little while ago.  

We're planning another release shortly, but want to investigate another bug before doing so.

Sorry for the inconvenience!

**Comment by scramjet** [comment]
No worries. Thanks!
