### ISSUE TITLE
error "refactor-nrepl is unable to build an AST for tools.analyzer encountered the following problem: org/osgi/framework/Version"

### ISSUE THREAD

**Issue by mhibti** [clojure-emacs/refactor-nrepl#207]
## Expected behavior
Replace symbol everywhere in the project

## Actual behavior
error message:
error "refactor-nrepl is unable to build an AST for tools.analyzer encountered the following problem: org/osgi/framework/Version"
## Steps to reproduce the problem
In my case I could get i every where therefore I'm not suspecting a bug but something wrong in my configuration. (I'm newbie in clojure)

### clj-refactor.el and refactor-nrepl version information
2.4.0  & 2.3.1
### CIDER version information
CIDER 0.16.0snapshot (package: 20171001.112)

CIDER's REPL is launched. Here's an example:*

WARNING: CIDER's version (0.16.0-snapshot) does not match cider-nrepl's version (0.14.0). Things will break!
         More information.
WARNING: clj-refactor and refactor-nrepl are out of sync.
Their versions are 2.4.0-SNAPSHOT (package: 20170720.712) and 2.3.1, respectively.
You can mute this warning by changing cljr-suppress-middleware-warnings.

### Leiningen or Boot version
2.7.1
### Emacs version

27.0.50
### Operating system

Debian

**Comment by expez** [comment]
Hi

I'm not sure what goes wrong, but `osgi` is probably doing all kinds of weird things that might trigger edge-cases in `tools.analyzer` which causes it to error out.

To verify that this is osgi-related, could you try  the tool in some clojure project that doesn't pull in that dependency?

**Comment by mhibti** [comment]
You are right !
In another project It worked.
Now I have to see where I use osgi.
thanks a lot !
