### ISSUE TITLE
Support find-symbol for arbitrary input (outside of buffer)

### ISSUE THREAD

**Issue by SevereOverfl0w** [clojure-emacs/refactor-nrepl#208]
find-symbol asks for file/column/symbol, it would be nice to allow inputting a symbol & the current namespace you're in (similar to cider-nrepl's info op), instead of using file/line/column of occurrence.

This would allow arbitrary user input, instead of mandating that the symbol is first written to a file.

**Comment by expez** [comment]
This is unfortunately impossible, because `tools.analyzer` needs to know which symbol to act on.  To uniquely determine a symbol it isn't enough to just say `foo`, you have to say `foo` in this file, at this location.

The other use case is also solved already by tools like `ag`, `ack` etc, which I use extensively too :)

**Comment by SevereOverfl0w** [comment]
There's no ability to tell tools analyser about the symbol by its full name? E.g. foo.bar/baz?

Ag, Ack has overlap. But it's not perfect, it has significant overlap with similarly named symbols.

Searching for `def ` includes defn, defmacro, etc. There's tricks around this of course, but it would be nice to not have to worry about that at all.

On 13 November 2017 09:05:52 GMT+00:00, Lars Andersen <notifications@github.com> wrote:
>This is unfortunately impossible, because `tools.analyzer` needs to
>know which symbol to act on.  To uniquely determine a symbol it isn't
>enough to just say `foo`, you have to say `foo` in this file, at this
>location.
>
>The other use case is also solved already by tools like `ag`, `ack`
>etc, which I use extensively too :)
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/clojure-emacs/refactor-nrepl/issues/208#issuecomment-343855319

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by expez** [comment]
> There's no ability to tell tools analyser about the symbol by its full name? E.g. foo.bar/baz?

No, `tools.analyzer` doesn't have such an interface I think, so we'd have to build one, and it would have some assumptions and limitations.  E.g. it would only work on top-level defs and assume that you meant the first occurrence.  This should be OK 99% of the time though :)

Anyway, I agree that this would be nice, to make it a bit easier to rename global symbols. 

IIRC the cider nrepl op provides location info.  Perhaps we can lookup the symbol with `info` and then pass the location info straight to `tools.analyzer`?

You want to get your hands dirty, @SevereOverfl0w? :)

**Comment by SevereOverfl0w** [comment]
Ha, yes. Looking at the source of the symbol might be a neat way to hack around it. With one _minor_ catch, you have to parse the `def*` form that introduces the symbol.

There's also a potential hack in writing a file to `/tmp/`, if it's really limiting from tools.analyzer.

I probably will get my hands dirty and dig in on this, yep. It seems like a universally useful feature.

**Comment by MalloZup** [comment]
autogenerated with https://github.com/MalloZup/doghub:  issue inactive since 450 days. Please update the issue or close it

**Comment by vemv** [comment]
I think this is hackable, https://github.com/clojure-emacs/refactor-nrepl/blob/master/src/refactor_nrepl/find/find_symbol.clj is the ns in question

https://github.com/clojure-emacs/refactor-nrepl/blob/1399da2029c2e875d450af4caa347302f55fa965/src/refactor_nrepl/find/find_symbol.clj#L232 does the filtering by line/column.

One could as well query the AST nodes by some other criteria. See https://github.com/clojure/tools.analyzer.jvm/blob/master/spec/ast-ref.edn

Closing the issue as it's been a long time, PRs welcome!
