### ISSUE TITLE
refactor-nrepl.middleware: java.lang.IllegalAccessError: err-info does not exist

### ISSUE THREAD

**Issue by vemv** [clojure-emacs/refactor-nrepl#214]
Hey there,

I started getting the title issue this morning. I guess it's due to me using `2.4.0-SNAPSHOT` (since a long time. I don't recall the exact reason why I wasn't not using 2.3.1) + recent commits.

[Full stacktrace](https://gist.githubusercontent.com/vemv/11445277034113388dd3f3bdce06ee0c/raw/f32ea70d0708b1374d82ccd2e8db15247bd5d667/-)

Let me know if I can help you. I hope 2.3.1 works fine for me, meanwhile.

Cheers - Victor

**Comment by benedekfazekas** [comment]
thanks for flagging. already fixed thanks to bbatsov and co. will deploy a new snapshot to clojars soon too

**Comment by vemv** [comment]
Awesome to hear!

Meanwhile, I cannot get Emacs/CIDER to work again under any setup:

- no refactor-nrepl
- r-n 2.3.1
- r-n 2.4.0 SNAPSHOT

I'd be thankful if you can release soon the latest known-good version f2e3fd5e21567b47f079017b47cebecc73f8124d as `2.4.0`, and today's commits as a new separate version

**Comment by benedekfazekas** [comment]
new snapshot version is on clojars. please give it spin and shout if still have problems

**Comment by benedekfazekas** [comment]
feel free to reopen if this reoccurs
