### ISSUE TITLE
deps.edn recognized as project root

### ISSUE THREAD

**Issue by mbuczko** [clojure-emacs/refactor-nrepl#219]
As mentioned before I'd like to handle new-style dependencies (https://clojure.org/guides/deps_and_cli) introduced recently by clojure core team. The first step is to recognize _deps.edn_ as a project root (as it's already done with _project.clj_, _build.boot_ and _pom.xml_).

My PR simply adds _deps.edn_ as one more recognizable project root and this way avoids NullPointerException when deps.edn-based project is loaded.

**Comment by expez** [comment]
Fixed in https://github.com/clojure-emacs/refactor-nrepl/commit/9b113754eea0fd980773f0736b3bbbeba939ad5c

Thanks @mbuczko!
