### ISSUE TITLE
Slamhound repackaging

### ISSUE THREAD

**Issue by bendlas** [clojure-emacs/refactor-nrepl#23]
If you subset and repackage slamhound, please also prefix it with you own namespace.
As it stands, slamhound cannot be used in parallel with refactor-nrepl.

(require 'slam.hound) throws slam.hound.regrow/regrow var not found.

thanks

**Comment by benedekfazekas** [comment]
fair point. thx for the report

**Comment by benedekfazekas** [comment]
uploaded to clojars
