### ISSUE TITLE
Make a release?

### ISSUE THREAD

**Issue by vemv** [clojure-emacs/refactor-nrepl#234]
Hey there,

the last release was more than a year ago. So I have to use `[refactor-nrepl "2.4.0-SNAPSHOT"]` to stay reasonably up-to-date, but at the same time, I fear that one day there will be breaking changes (maybe subtle/unplanned ones).

Probably a year's worth of improvements is worth releasing, sounds good?

Thanks - Victor

**Comment by bbatsov** [comment]
I planned to cut a release this week, but I’m buried with other stuff. I
Lars and Benedek don’t beat me to it, I’ll cut the release some time next
week. Hopefully. :-)

**Comment by bbatsov** [comment]
From Norway with love - the new release is out!

**Comment by expez** [comment]
Thanks @bbatsov :)
