### ISSUE TITLE
clean-ns does not deal with (:gen-class) methods' metadata 

### ISSUE THREAD

**Issue by carlosgeos** [clojure-emacs/refactor-nrepl#235]
Using `clj-refactor` I realised I could not use metadata in `(:gen-class :methods)` for example. The namespace cleaning puts it at the beginning of the `(ns)` form.

## Initial ns (took it from a test and modified it a bit)
```clojure
(ns resources.ns2
  (:gen-class
   :methods [^:static [handler [String] String]])   ;; <-- metadata here !
  (:require
   [clojure.pprint :refer [fresh-line]]
   [clojure.pprint :refer [get-pretty-writer]]
   [clojure.pprint :refer [cl-format]]
   [clojure.pprint :refer [get-pretty-writer fresh-line cl-format]]
   [clojure.instant :refer [read-instant-calendar]]
   [clojure.instant :refer :all]
   [clojure
    [instant :refer :all]
    [pprint :refer [cl-format]]]
   [clojure.test.junit :refer [with-junit-output]])
  (:use clojure.test
        clojure.test
        [clojure.string :rename {replace foo
                                 reverse bar}]
        [clojure.edn :rename {read-string rs
                              read rd}])
  (:import java.text.Normalizer))

(defn use-everything []
  (get-pretty-writer)
  (fresh-line)
  (cl-format)
  (compose-fixtures)
  (escape)
  (read-instant-date)
  (rs)
  java.text.Normalizer$Form/NFD)
```
## Expected behavior

```clojure
(ns resources.ns2
  (:gen-class
   :methods [^:static [handler [String] String]])
  (:require [clojure
             [edn :refer :all :rename {read-string rs}]
             [pprint :refer [cl-format fresh-line get-pretty-writer]]])
  (:import java.text.Normalizer))
```
## Actual behavior
```clojure
(ns ^:static resources.ns2 ;; <-- This is wrong !
  (:gen-class
   :methods [[handler [String] String]])
  (:require [clojure
             [edn :refer :all :rename {read-string rs}]
             [pprint :refer [cl-format fresh-line get-pretty-writer]]])
  (:import java.text.Normalizer))
```
## Steps to reproduce the problem

Run `(pprint-ns (clean-ns NS))` on some NS with that form.

### clj-refactor.el and refactor-nrepl version information

clj-refactor 2.4.0 (package: 20190117.1235), refactor-nrepl 2.4.0

### CIDER version information

CIDER 0.21.0snapshot (package: 20190116.1142)

### Leiningen or Boot version

Leiningen 2.8.3 on Java 1.8.0_92 Java HotSpot(TM) 64-Bit Server VM

### Emacs version

GNU Emacs 26.1 (build 1, x86_64-apple-darwin18.2.0, Carbon Version 158 AppKit 1671.2) of 2019-01-03

### Operating system

Hannah Montana Linux

### PR

I'll submit a PR soon to fix this. This is the culprit:

https://github.com/clojure-emacs/refactor-nrepl/blob/2f52c9e98e3cd5496d5f1c98e88816d6b4a1a724/src/refactor_nrepl/core.clj#L253-L270

**Comment by benedekfazekas** [comment]
superb report. thanks. pr is welcome
