### ISSUE TITLE
Retrieving libraries does not work in Java > 8

### ISSUE THREAD

**Issue by carlosgeos** [clojure-emacs/refactor-nrepl#237]
## The problem
`http-kit` version 2.2.0 does not like Java > 8.

`http-kit` version 2.3.0 does.

## Expected behavior
Shows the list of available libraries

## Actual behavior
```
Retrieving list of available libraries...
Error in nrepl-refactor: clojure.lang.Compiler$CompilerException: Syntax error compiling at (mranderson048/http_kit/v2v2v0/org/httpkit/client.clj:1:1).
#:clojure.error{:phase :compile-syntax-check, :line 1, :column 1, :source "mranderson048/http_kit/v2v2v0/org/httpkit/client.clj"}
 at clojure.lang.Compiler.load (Compiler.java:7647)
    clojure.lang.RT.loadResourceScript (RT.java:381)
    clojure.lang.RT.loadResourceScript (RT.java:372)
    clojure.lang.RT.load (RT.java:463)
```
## Steps to reproduce the problem
`cljr-add-project-dependency` or some other command that uses http-kit AND have Java 9, Java 10 or Java 11.
### clj-refactor.el and refactor-nrepl version information

`clj-refactor 2.4.0 (package: 20181224.1310), refactor-nrepl is unreachable`

### CIDER version information

```
;; CIDER 0.21.0snapshot (package: 20190116.1142), nREPL 0.5.3
;; Clojure 1.10.0, Java 11.0.2
```
### Leiningen or Boot version

`Leiningen 2.8.3 on Java 11.0.2 OpenJDK 64-Bit Server VM`

### Emacs version

26.1

### Operating system

TempleOS

## Related issues

- https://github.com/http-kit/http-kit/issues/387 (most relevant)
- https://github.com/http-kit/http-kit/issues/356

**Comment by NonaryR** [comment]
Hello, still working on the newest versions, see [here](https://github.com/clojure-emacs/clj-refactor.el/issues/435#issuecomment-480317073)
