### ISSUE TITLE
Hot loading workaround documentation is gone

### ISSUE THREAD

**Issue by credmp** [clojure-emacs/refactor-nrepl#254]
Hi, 

in issue #206 (https://github.com/clojure-emacs/refactor-nrepl/issues/206#issuecomment-411111041) you mention dropping the support for hot-loading dependencies. In the current versions indeed a message is shown that it has to be fixed to work with Java 10(+).

In the post you link to a workaround doc here (http://nrepl.readthedocs.io/en/latest/usage/#hot-loading-dependencies). This document is no longer available. I would really like to hotload dependencies once again, can you post the workaround instructions here so other people will be able to find it as well?

Cheers,

Arjen

**Comment by benedekfazekas** [comment]
seems the docs are moved to nrepl's own domain. this seems to be the right link now: https://nrepl.org/nrepl/0.6.0/usage/misc.html#_hot_loading_dependencies

hope this helps
