### ISSUE TITLE
`cljr-add-project-dependency` blows up when parsing Clojar artifacts

### ISSUE THREAD

**Issue by andersenleo** [clojure-emacs/refactor-nrepl#255]
Cross-posting here.

Sorry for skipping the report template - all details should be in the linked Github issue:

https://github.com/syl20bnr/spacemacs/issues/12385

Should also add that I'm running OpenJDK 8 (AdoptOpenJDK).

**Comment by benedekfazekas** [comment]
thanks for this. although as [this comment](https://github.com/syl20bnr/spacemacs/issues/12385#issuecomment-498731607) says the referenced lib's name is somewhat [borked](https://clojars.org/trident/1.1). I suppose if the issue can not be reproduced with well named libs I will close this.

**Comment by andersenleo** [comment]
I understand that approach. At the same time -- if the library was able to be uploaded to Clojars with that format.. wouldn't that indicate that `[trident/1.1 "jobryant"]` is a valid artifact coordinate and should be "parsable" by refactor-nrepl?

Would it be possible to dump a warning (and ignore) "borked" artifact names when parsing rather than crashing the artifact listing entirely?

**Comment by benedekfazekas** [comment]
valid point. not sure it worths the effort tho as naming this artifact "1.1" was almost surely not the intention of the author. Happy to look at/accept a PR for this tho.

**Comment by andersenleo** [comment]
Well - I guess something must be done. The function (which at least *I* use frequently) is useless until it's either fixed in refactor-nrepl or the library is taken down from Clojars :-)

I'll give the PR a try!

**Comment by benedekfazekas** [comment]
ah just realised I misunderstood the situation, sorry. This happens when we retrieve version info from clojars so this brakes the feature for everybody.  Also as far as I remember clojars is immutable -- altho this is possible a good case for an exception of this rule.

I would also try to raise this with the author of the lib and maybe clojars maintainers. But PR is still very welcome.

**Comment by benedekfazekas** [comment]
Seems the author got notified already jacobobryant/trident#4

**Comment by andersenleo** [comment]
Sweet 👍. PR is inbound in a couple of minutes.

**Comment by jacobobryant** [comment]
Hi. Author of the borked lib here. Yes, I accidentally mixed up the artifact-id and version on that one. Sorry about that. Unfortunately I can't take it down from Clojars since they only delete artifacts when they contain vulnerabilities/private credentials.

**Comment by jacobobryant** [comment]
FYI, the Clojars docs give the regexes they use to check group/artifact/version here: https://github.com/clojars/clojars-web/wiki/About#what-is-the-legal-format-for-a-group-or-project-name
So I'd recommend updating `refactor-nrepl` to be in line with that
(Interestingly, while "Project and group names must consist solely of ASCII lowercase letters, numbers, hyphens, and underscores", the regex they provide includes a period, which I'm guessing is where `refactor-nrepl` trips up)

**Comment by andersenleo** [comment]
Simple hack to work around the issue in the PR above ☝️.
