### ISSUE TITLE
cljr-project-clean asks for `File to save in` everytime

### ISSUE THREAD

**Issue by thiagokokada** [clojure-emacs/refactor-nrepl#260]
## Expected behavior

Shouldn't ask anything when `M-x cljr-project-clean` is called .

## Actual behavior

When calling `M-x cljr-project-clean`, it asks for `File to save in` for every file that is cleaned.

## Steps to reproduce the problem

When calling `M-x cljr-project-clean`, it asks for `File to save in` for every file that is cleaned.

### clj-refactor.el and refactor-nrepl version information

```clj-refactor 2.5.0-SNAPSHOT (package: 20190618.716), refactor-nrepl 2.5.0-SNAPSHOT```

### CIDER version information

```
;; CIDER 0.22.0snapshot (package: 20190619.745), nREPL 0.6.0
;; Clojure 1.10.1, Java 1.8.0_212
```

### Emacs version

```GNU Emacs 26.1 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.24.5) of 2019-06-16```

### Operating system

```
$ cat /etc/os-release
NAME=NixOS
ID=nixos
VERSION="19.03.172921.d77e3bd6613 (Koi)"
VERSION_CODENAME=koi
VERSION_ID="19.03.172921.d77e3bd6613"
PRETTY_NAME="NixOS 19.03.172921.d77e3bd6613 (Koi)"
LOGO="nix-snowflake"
HOME_URL="https://nixos.org/"
SUPPORT_URL="https://nixos.org/nixos/support.html"
BUG_REPORT_URL="https://github.com/NixOS/nixpkgs/issues"
```

**Comment by reutsharabani** [comment]
I am experiencing this as well. I work with spacemacs but I'm not sure its related.

**Comment by rinconjc** [comment]
This seems to be a bug in [clj-refactor.el](https://github.com/clojure-emacs/clj-refactor.el/blob/master/clj-refactor.el#L2749).

**Comment by vemv** [comment]
Also tracked in https://github.com/clojure-emacs/clj-refactor.el/issues/139
