### ISSUE TITLE
Make Artifacts Cache Durable

### ISSUE THREAD

**Issue by paulrd** [clojure-emacs/refactor-nrepl#263]
Hi this is a feature request. Would it be possible to make the artifacts cache durable (write to local file) so that https://clojars.org/repo/all-jars.clj is not downloaded every time cider jacks-in? I have the bad habit of restarting the cider repl many times and that's 4MB each time and I have to pay a lot for bandwidth. Also, bandwidth could be saved by downloading the gzipped version which is a fraction (1/8th) the size (500KB) https://clojars.org/repo/all-jars.clj.gz.

**Comment by paulrd** [comment]
I can give this a shot. It just needs to write a timestamp to a file and switch to using gzip.

**Comment by expez** [comment]
Hi, this sounds like a good idea to me.

We can do either or both.  Do keep in mind that you have to check for the presence of gzip before running the new code path.  Especially our users on Windows are unlikely to have that utility available on path for emacs to use.
