### ISSUE TITLE
Warning of illegal reflective access on Java 12

### ISSUE THREAD

**Issue by piranha** [clojure-emacs/refactor-nrepl#265]
refactor-nrepl currently uses orchard 0.4.0, which bundles old dynapath, which causes Java 12 to spit following warning:

```
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by mranderson048.orchard.v0v3v0.dynapath.v0v2v5.dynapath.defaults$eval28489$fn__28490 to method java.net.URLClassLoader.addURL(java.net.URL)
WARNING: Please consider reporting this to the maintainers of mranderson048.orchard.v0v3v0.dynapath.v0v2v5.dynapath.defaults$eval28489$fn__28490
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
```

I wonder if it's possible to update to a newer orchard, to remove this warning? :) I guess it's impossible to do in my project.clj because this dependency is inlined, right?

**Comment by bbatsov** [comment]
Yep, the orchard dependency has to be updated in `refactor-nrepl`. This should be pretty straightforward.

**Comment by mbuczko** [comment]
Fixed in https://github.com/clojure-emacs/refactor-nrepl/pull/276
