### ISSUE TITLE
find-symbol doesn't work on option maps

### ISSUE THREAD

**Issue by expez** [clojure-emacs/refactor-nrepl#27]
I tried renaming one of the keys in an options map earlier today and that didn't work. 

Renaming a regular destructured map works fine.  Renaming `bar` below also works fine:

```clj
(defn foo [& {:keys [bar]}]
  bar)
```

but renaming `bar` doesn't work in this case:

```clj
(defn foo [& {:keys [bar] :or {bar "bar"}}]
  bar)
```

This borders on #wontfix

**Comment by benedekfazekas** [comment]
hm... having a look on the generated AST deffo makes sense. I'll do that when have a bit of time

**Comment by benedekfazekas** [comment]
this is turned into

```clojure
(let* [map__36023 p__36021 map__36023 (if (clojure.core/seq? map__36023) (clojure.lang.PersistentHashMap/create (clojure.core/seq map__36023)) map__36023) bar (clojure.core/get map__36023 :bar "bar")] bar)
```

so basically the :or part will be `(get map_blalba :bar "bar")` no bar symbol whatsoever... don't see any other way than handling this separately

**Comment by benedekfazekas** [comment]
i might just fix this in find local symbols specially looking for `(keyword (name symbol))` in the right subtree of the AST

**Comment by expez** [comment]
Perhaps this is a general problem with destructuring?  E.g. if this was in a let-binding with map destructuring and a default map we might see the same problem.

**Comment by benedekfazekas** [comment]
could well be. will try to find a generic solution in find local symbol

**Comment by benedekfazekas** [comment]
I put this on hold. even if i successfully find the node representing the code defining the default value the location information on that node is pointing back to the symbol in the keys vector. created TANAL issue for this: http://dev.clojure.org/jira/browse/TANAL-111

**Comment by benedekfazekas** [comment]
i played around running with my own very simplistic analyzer keeping track of location info, hoping to do a workaround, but could not find an easy win..
