### ISSUE TITLE
Get rid of find-local-symbol and var-info?

### ISSUE THREAD

**Issue by expez** [clojure-emacs/refactor-nrepl#28]
@benedekfazekas

I'm having a hard time finding a use-case for `find-local-symbol` on its own.  Is there any point in providing this?

Now that we're depending on cider-nrepl, is there any reason to keep the rather anemic `var-info` around?

**Comment by benedekfazekas** [comment]
`var-info` is a halfdone try to reimplement var-info on AST basis in order to eliminate the cider middleware dependency. did not quite work out...

`find-local-symbol` fair point. depends on the client really... you are right we might not want to expose it on the middleware interface

**Comment by benedekfazekas** [comment]
nice one!
