### ISSUE TITLE
Fix the build and get another snapshot out

### ISSUE THREAD

**Issue by expez** [clojure-emacs/refactor-nrepl#282]
The build presently fails when attempting to publish a new snapshot:

Specifically, `./build.sh deploy clojars`, results in:

```
Ran 109 tests containing 263 assertions.
4 failures, 1 errors.
```

It fails well before it asks for clojars credentials, so this is something anyone can work on.

//cc @mbuczko 🙏

**Comment by mbuczko** [comment]
@expez could you paste those failures/errors? I was able to deploy snapshot with no problem:
https://clojars.org/mbuczko/refactor-nrepl/versions/2.5.0-SNAPSHOT

**Comment by expez** [comment]
Perhaps this has been fixed by the recent changes.  I'm traveling right now and can't give this a shot unfortunately.  Perhaps @bbatsov or @benedekfazekas can give it a go?

**Comment by bbatsov** [comment]
The build failed for me locally when I briefly tested it yesterday. Btw, the Makefile is broken, as it doesn't apply MrAnderson before deploying. 

I'll take a closer look when I can.

**Comment by bbatsov** [comment]
A new snapshot is out, btw, despite the failing tests. I've also fixed the Makefile.

**Comment by bbatsov** [comment]
Actually on my second computer the tests actually pass. Weird. :-)

**Comment by expez** [comment]
> Actually on my second computer the tests actually pass. Weird. :-)

Ugh.  Put it somewhere safe and don't update anything so we have a way of cutting a release 🙄

**Comment by bbatsov** [comment]
You're welcome. Unfortunately, I also figured out that the tests are failing with nREPL 0.6, although everything works just fine with it. Guess we'll have to investigate this down the road.

**Comment by bbatsov** [comment]
2.5.0 is out. I guess we can close this issue now.
