### ISSUE TITLE
Problems with 2.5.0-snapshot and cider-jack-in

### ISSUE THREAD

**Issue by AndreaCrotti** [clojure-emacs/refactor-nrepl#283]
## Expected behavior
cider-jack-in working correctly.

## Actual behavior

cider-jack-in throwing an exception.

## Steps to reproduce the problem
Just running this command in the terminal also fails:

/usr/local/bin/lein update-in :dependencies conj \[nrepl\ \"0.6.0\"\] -- update-in :plugins conj \[refactor-nrepl\ \"2.5.0-SNAPSHOT\"\] -- update-in :plugins conj \[com.billpiel/sayid\ \"0.0.18\"\] -- repl :headless :host localhost

Where the error is
```Caused by: java.lang.IllegalAccessError: reader-error does not exist
 at clojure.core$refer.invokeStatic (core.clj:4249)...```

Changing refactor-nrepl to 2.4.0 fixes it though:

/usr/local/bin/lein update-in :dependencies conj \[nrepl\ \"0.6.0\"\] -- update-in :plugins conj \[refactor-nrepl\ \"2.4.0\"\] -- update-in :plugins conj \[com.billpiel/sayid\ \"0.0.18\"\] -- repl :headless :host localhost

**Comment by AndreaCrotti** [comment]
After some bisecting installing the library locally I found that this is the commit that broke things:
https://github.com/clojure-emacs/refactor-nrepl/commit/75f5255f0e4e701f50d30cc58216e03c2d558905

**Comment by expez** [comment]
I think maybe a bad snapshot was published, where the inlining of dependencies wasn't performed.  

Thanks for investigating!

**Comment by AndreaCrotti** [comment]
if anyone wants a workaround in the meanwhile it's quite easy:
- checkout this project locally
- git checkout e35af1d1b972cfecbf5e857384234ac3f683652d to get to a working version
- lein install to install it in your maven dir (overriding the 2.5.0-SNAPSHOT that would be downloaded)

**Comment by bbatsov** [comment]
> I think maybe a bad snapshot was published, where the inlining of dependencies wasn't performed.

Yeah, exactly. I broke this because I used `make deploy` with the assumption it was going to do the inlining. I'll fix it when I can.

**Comment by bbatsov** [comment]
I fixed the Makefile and deployed a new build.
