### ISSUE TITLE
rename-symbol times out when namespaced keywords are present

### ISSUE THREAD

**Issue by beluchin** [clojure-emacs/refactor-nrepl#289]
the `rename symbol` refactoring times out when the surrounding `let` form contains a map destructuring with namespaced keywords

To reproduce, attempt to rename the `a` symbol below:
```
(let [a 1
      {::core/keys [a-key another]} a-map])
```
clj-refactor.el and refactor-nrepl version information:
`clj-refactor 2.5.0 (package: 20200405.1419), refactor-nrepl 2.5.0`

CIDER version information:
```
CIDER 0.25.0 (Bergamo), nREPL 0.7.0
Clojure 1.10.1, Java 1.8.0_171
```

Leiningen version
`Leiningen 2.9.4 on Java 1.8.0_171 Java HotSpot(TM) 64-Bit Server VM`

Emacs version:
`GNU Emacs 26.1 (build 1, x86_64-apple-darwin14.5.0, NS appkit-1348.17 Version 10.10.5 (Build 14F2511))
 of 2018-05-30`

Operating system:
MacOS 10.15.6

**Comment by expez** [comment]
Most likely due to lack of support in tools.analyzer.  The version we've been using is quite old.

Thanks for the report!

**Comment by expez** [comment]
@Bronsa What's the latest with `tools.analyzer`?  It looks like it's still maintained, but only trivial version bumps are happening.  If someone fixes this and submits a patch (along with signing the contributor agreement) is it likely to get merged and a new release cut?

**Comment by vemv** [comment]
FWIW from Eastwood experience I don't have the impression that t.ana chokes on namespaced keywords usage.

Might be related to how t.ana is wrapped? Reading the our codebase, I have the impression that `*ns*` can be used as a fallback when `find-ns <target-ns>`  returns nil.

And I didn't find a prior binding of `*ns*` to the "target ns" which would make `*ns*` correct. IOW, that var would point to an unrelated ns.

A possible explanation is that one is hitting a namespace that hasn't been `require`d before, making `find-ns` fail.

(This is where a "reloaded" workflow helps)
