### ISSUE TITLE
Split refactor.clj into 3 distinct ops

### ISSUE THREAD

**Issue by expez** [clojure-emacs/refactor-nrepl#29]
We now have a single op `refactor` in this namespace but then we branch on `refactor-fn` too.  It would be much better if we had 3 distinct ops.  This would make it possible to have a more meaningful `descriptor`, making `refactor-nrepl` more self-documenting, as well as making it possible to return more semantically meaningful return values than `value`, e.g. `:occurrences`.

**Comment by bbatsov** [comment]
:+1:

**Comment by benedekfazekas** [comment]
fair point. however, would not this be a breaking change for clients?

**Comment by expez** [comment]
Yes, which is why we should do this before we release 1.0.

**Comment by magnars** [comment]
:+1:

**Comment by benedekfazekas** [comment]
as we have a new client in the works @rundis needs to be notified about this then

**Comment by expez** [comment]
Perhaps we should be prefixing our ops, to avoid collisions with other middleware, while we're at it?

**Comment by rundis** [comment]
Tx for being kept in the loop !

Sounds like a good idea to me. Actually tripped me up the first time.
(in any case I won't release my Light Table plugin until you guys publish  the next version)
