### ISSUE TITLE
`namespace-aliases` could guard against unreadable files

### ISSUE THREAD

**Issue by vemv** [clojure-emacs/refactor-nrepl#291]
## Brief

`namespace-aliases` i.e. the defn that backs `cljr-slash`, breaks if there's any .clj file with invalid syntax in a given project.

There's kind of a legitimate use case for .clj files with invalid syntax:

* template files, e.g. `moustache`d clojure
* more importantly, WIP code.

As an aggraviating condition, cljr-slash [omits errors](https://github.com/clojure-emacs/clj-refactor.el/blob/9dcc50da7ce6f3c10276c87f09022e80c03e8bef/clj-refactor.el#L1929), making this issue hard to debug / easy to forget.

So, `namespace-aliases` could omit files with invalid syntax, instead of throwing exceptions in presence of these files

## Steps to reproduce the problem

* `echo "totally-invalid(((((((" > src/sample.clj` 
* invoke `refactor-nrepl.ns.libspecs/namespace-aliases`

## Suggestion

In:

https://github.com/clojure-emacs/refactor-nrepl/blob/dbafd6e686402dc020d7026e21ee556812fc51da/src/refactor_nrepl/ns/libspecs.clj#L50

augment the `(some-fn ...)`, with `(every-pred readable? (some-fn ...))`, where `readable?` is a defn that tries reading the ns form with tools.reader + tools.namespace.parse, returning false if any exception would have been thrown.

### clj-refactor.el and refactor-nrepl version information

Both repos @ `master`

**Comment by bbatsov** [comment]
PR welcome!
