### ISSUE TITLE
Test failures on Clojure 1.8

### ISSUE THREAD

**Issue by bbatsov** [clojure-emacs/refactor-nrepl#293]
After updating all the outdated deps I've noticed that some tests are currently failing on Clojure 1.8 (mostly related to `refactor_nrepl.extract_definition`). I didn't have time to investigate this, but I guess it should be relatively simple to track this down.

**Comment by vemv** [comment]
Fixed with https://github.com/clojure-emacs/refactor-nrepl/commit/ff52d03e5ff61b12849622708c7aab4f34f009ec
