### ISSUE TITLE
Remove find-referred?

### ISSUE THREAD

**Issue by expez** [clojure-emacs/refactor-nrepl#30]
@benedekfazekas 

This doesn't appear to be used in the current version of `clj-refactor`, can we just delete it?

The readme states that it was added as a temporary performance fix for `clj-remove-unused-requires` and is likely to get deleted.

**Comment by benedekfazekas** [comment]
hm... tried to quickly find out when it got removed... (as remove requires is still around it might make sense to use it there). but you are right it is not used anymore so it can be removed

**Comment by benedekfazekas** [comment]
thx!
