### ISSUE TITLE
Get another snapshot release out

### ISSUE THREAD

**Issue by expez** [clojure-emacs/refactor-nrepl#304]
Created another issue for the discussion that started in #301.

 Seems we might have some trouble with mranderson?

@bbatsov did a standard deploy yet the artifact isn't usable and seems to look a bit different:

![image](https://user-images.githubusercontent.com/1006557/123539758-7de2f400-d73b-11eb-9d27-739d83f7d3fc.png)

all the `.class` files of the inlined deps are gone.  

Is this normal @benedekfazekas (mranderson has had several releases since our last working snapshot was built) or is that a clear indication that something went wrong?

**Comment by benedekfazekas** [comment]
had just a quick look and `cider-nrepl` uses the same version of mranderson, maybe the makefile or the created dir structure is different for the two projects (assuming this works fine for `cider-nrepl`). will try to find time to have a proper look

**Comment by benedekfazekas** [comment]
looking at the latest 3.0.0-SNAPSHOT from @bbatsov I can see plenty of `.class` files none for cljfmt tho

**Comment by expez** [comment]
Just tried the snapshot @bbatsov just published:

![image](https://user-images.githubusercontent.com/1006557/123631660-4c3f5b00-d817-11eb-9f87-937292249f29.png)

Has anyone else tested?  I'm probably the only one on Windows, so maybe the regression is specific to that OS?

**Comment by benedekfazekas** [comment]
I also don't see any class files in cljfmt 0.7.0 jar in itself

**Comment by expez** [comment]
> I also don't see any class files in cljfmt 0.7.0 jar in itself

Does the snapshot work for you?

You can do 

```el
(setq cider-jack-in-lein-plugins 
  (("refactor-nrepl/refactor-nrepl" "3.0.0-SNAPSHOT" :predicate cljr--inject-middleware-p)
   ("cider/cider-nrepl" "0.26.0-SNAPSHOT")))
```

to test from emacs.

**Comment by vemv** [comment]
Released https://clojars.org/refactor-nrepl/versions/3.0.0-alpha1 with master + https://github.com/clojure-emacs/refactor-nrepl/pull/329
