### ISSUE TITLE
clean-ns doesn't handle require macro ?

### ISSUE THREAD

**Issue by rundis** [clojure-emacs/refactor-nrepl#31]
if you use require rather than :require in your ns definition, no cleanup is suggested.
[pprint.clj](https://github.com/clojure-emacs/refactor-nrepl/blob/a40b1631fa5bb95d0429555679d110a43bbcee4e/src/refactor_nrepl/ns/pprint.clj#L94) might be one of the culprits ?

**Comment by benedekfazekas** [comment]
is not it wrong/bad policy to use `(require)` in the ns macro tho?

**Comment by magnars** [comment]
maybe clean-ns could replace `require` with `:require`? It does everything else already, so ... ;-)

**Comment by rundis** [comment]
@benedekfazekas :require is the idiomatic approach, but require is certainly allowed :) 
I would be in favor of replace require with :require (and import with :import etc), alternatively give a heads up in the clean-ns doc about when/why you won't get a result when you might expect one !

**Comment by benedekfazekas** [comment]
:+1:

**Comment by expez** [comment]
This should be easy to fix, I think a small tweak of the grammar is all that is needed, but why would we add support for undocumented edgecases?  The fact that symbols are supported seems like an implementation detail to me.

**Comment by rundis** [comment]
No, require doesn't work in clojurescript :)

I agreed it's definitely an edge case. Not sure I agreed it's undocumented ([ref](https://clojuredocs.org/clojure.core/require) but it does state _"Use :require in the ns macro in preference to calling this directly"_) 

Anyways I have no problem understanding why you wouldn't feel an urge to add support for this ! 
Feel free to close this issue if you don't think it's worth the effort to support it.

cheers
Magnus

**Comment by expez** [comment]
What is meant in the documentation for `require` is that this:

```clj 
(ns foo
  (:require 'bar))
```

should be preferred to this:

```clj
(ns foo)

(require 'bar)
```

At least that is my reading.

I really appreciate your bug reports @rundis.  Getting another client for `refactor-nrepl` is flushing out some interesting edgecases :+1:
