### ISSUE TITLE
Make the tests run locally again under Windows

### ISSUE THREAD

**Issue by expez** [clojure-emacs/refactor-nrepl#312]
This snippet:

```clj
(ns global-test-setup
  "This namespace's contents will be automatically loaded by `lein test` (or any test runner)."
  (:require
   [refactor-nrepl.inlined-deps.toolsnamespace.v1v1v0.clojure.tools.namespace.repl :refer [set-refresh-dirs]]))
```

references an ns that doesn't exist until mranderson has run.

My current side project is Windows only and mranderson doesn't run on Windows.  The presence of his ns therefore
makes it impossible to run the tests locally.  Using the CI server to test that everything is OK makes the feedback loop quite a bit slower.

Why is this ns referencing a namespace that doesn't exist?

I also don't get this part:

```clj
(when (System/getenv "CI") ; don't alter local environments (which may also use clojure.tools.namespace.repl)
  ;; Intentionally exclude the `lein-plugin/` source path:
  (set-refresh-dirs "src" "test"))
```

Why would we need a refresh dir to be set on the CI server instead of locally?  It looks like this NS is a noop as written.  Can we just remove this file?

**Comment by vemv** [comment]
Context is https://github.com/clojure-emacs/refactor-nrepl/pull/298 which not only fixed the build but also added a fairly important new feature for having more a robust end-user experience

Let's fix it like this:

```
try refering set-refresh-dirs from refactor-nrepl.inlined-deps.toolsnamespace.v1v1v0.clojure.tools.namespace.repl
else if we're not in a CI env refer set-refresh-dirs from clojure.tools.namespace.repl 
else fail
```
