### ISSUE TITLE
Don't avoid 1-element vectors/lists

### ISSUE THREAD

**Issue by vemv** [clojure-emacs/refactor-nrepl#344]
https://github.com/clojure-emacs/refactor-nrepl/pull/308 started going more into the [how to ns](https://stuartsierra.com/2016/08/27/how-to-ns) direction, however there's still a difference:

![image](https://user-images.githubusercontent.com/1162994/138682080-1b59635a-9d0f-4371-8d7d-902a6b6e383d.png)

I'd say we should favor lists/vectors (as opposed to unwrapping elements) so that:

* we don't contribute to a proliferation of styles
* things are sortable via `M-x sort-lines`
  * else it won't meaningfully sort in mixed presence of colls vs. symbols.
* indentation is consistent.

This particularly matters because e.g. `rename-file-or-dir` always performs a clean-ns, so renaming a ns should not change other aspects of its ns form (presumably formatted/linted with a variety of tools).

**Comment by camsaul** [comment]
Is there some way to disable this change so we can keep the old functionality?

**Comment by vemv** [comment]
We can introduce a feature flag (which would have to be settable from clj-refactor.el also), PRs welcome as well

btw would appreciate https://github.com/camsaul/whitespace-linter/issues/9 - might be a fair exchange 😇
