### ISSUE TITLE
Consider version tagging git repo for all official releases

### ISSUE THREAD

**Issue by lread** [clojure-emacs/refactor-nrepl#357]
## Observation
I see [refactor-nrepl 3.1.0 has been published to clojars](https://clojars.org/refactor-nrepl/versions/3.1.0) but there is no equivalent `v3.1.0` tag on this GitHub repo.

## Background 
I try to keep rewrite-clj canary tests up to date.
Canary testing downloads the source code of libraries that use rewrite-clj and then runs their tests against rewrite-clj master.
The current process that works for all other libs under canary test is checking the git tag version or GitHub release version.

## Proposal
Always tag the GitHub repo with the version of each published release.

This would help me to help you, it reduces the chances of me introducing any changes to rewrite-clj that might break refactor-nrepl.

## Alternatives
I did at one point explore looking at the clojars pointer back to scm (usually GitHub) (effectively the pom `scm` `url` + `tag`) but found that this info was sometimes not populated, and if so, often incorrect.

**Comment by vemv** [comment]
Is using antq or simply `:mvn/version "RELEASE"` an alternative?

**Comment by vemv** [comment]
Likewise is pulling `master` latest an alternative? You can rest assured that everything that gets into master is stable. Might be particularly convenient: you'd get an even faster feedback loop.

**Comment by lread** [comment]
Thanks for the replies and ideas @vemv.

Antq does not work for me, I need the lib source with tests.

Pulling master does not work for me. 
I'm only interested in canary testing official releases of libs against rewrite-clj master.
Testing against the master of libs can mean testing against works in progress and that's not something I want to entertain.

**Comment by bbatsov** [comment]
> Always tag the GitHub repo with the version of each published release.

I thought we always did this, so I guess that's just an oversight. Generally it's also a good idea to associate the release notes with the tag.

**Comment by lread** [comment]
> > Always tag the GitHub repo with the version of each published release.
> 
> I thought we always did this, so I guess that's just an oversight. Generally it's also a good idea to associate the release notes with the tag.

Cool, thanks, that's what I expected.

If you folks want to automate release flows, you might find inspiration from slipset's work on clj-commons. I can dig up the deets if you are interested. Borkdude took inspiration from his work and I think Sean Corfield recently automated his release flows too.

**Comment by bbatsov** [comment]
I saw the article (https://slipset.github.io/posts/deploying-to-clojars), but never had time to apply it. I think all the projects here can benefit from some release automation as I do several steps manually for each release and this is both time-consuming and error-prone.

**Comment by lread** [comment]
Yeah, that's it!

@bbatsov, I took a different approach for my projects, I have a GitHub Action Release workflow which is clicked from the GitHub UI. It invokes a GitHub release workflow ([example](https://github.com/clj-commons/rewrite-clj/blob/main/.github/workflows/release.yml) with supporting [bb task](https://github.com/clj-commons/rewrite-clj/blob/main/script/ci_release.clj)) that:

- sanity tests that we are good for release (currently this is validating that change log describes release)
- computes the version
- creates the jar (with correct scm in pom)
- updates version in changelog and any other docs
- deploys jar to clojars
- commits changes made to docs
- version tags the git repo
- and finally informs cljdoc of the new release

This works nicely for me and I like all the automated steps, but in hindsight, I think I prefer the slipset approach because its invocation is not tied to a specific CI vendor UI.

If you are interested and can figure out a way I can help to automate your deploys, lemme know.

**Comment by lread** [comment]
Yeah, that's it!

@bbatsov, I took a different approach for my projects, I have a GitHub Action Release workflow which is clicked from the GitHub UI. It invokes a GitHub release workflow ([example](https://github.com/clj-commons/rewrite-clj/blob/main/.github/workflows/release.yml) with supporting [bb task](https://github.com/clj-commons/rewrite-clj/blob/main/script/ci_release.clj)) that:

- sanity tests that we are good for release (currently this is validating that change log describes release)
- computes the version
- creates the jar (with correct scm in pom)
- updates version in changelog and any other docs
- deploys jar to clojars
- commits changes made to docs
- version tags the git repo
- and finally informs cljdoc of the new release

This works nicely for me and I like all the automated steps, but in hindsight, I think I prefer the slipset approach because its invocation is not tied to a specific CI vendor UI.

If you are interested and can figure out a way I can help to automate your deploys, lemme know.

**Comment by vemv** [comment]
Tags are now mandatory for being able to perform `make deploy`, it's a setup I have in a few projects

https://github.com/clojure-emacs/refactor-nrepl/blob/fd34cfe32b6aaf690e2f1ec75a8f2db05a08444b/Makefile#L47-L68
