### ISSUE TITLE
clean-namespace is failing in CLJS and CLJ projects

### ISSUE THREAD

**Issue by dgtized** [clojure-emacs/refactor-nrepl#363]
After upgrading to latest clj-refactor today, I started getting an error after invoking cljr-clean-ns in both CLJ and CLJS projects. The error is `if: Don’t know how to create ISeq from: clojure.core$memoize$fn__6894`.

Given the timing of when this behavior appeared and the error message itself mentioning memoize, I'm a bit suspicious of unexpected side effects from https://github.com/clojure-emacs/refactor-nrepl/pull/361/files#diff-035aaed83c906822f30146de70e4bf30dea2ae463de4aed2927bd9d0e2383e55R25. However, I did also upgrade some other things today, so it's possible that's a red herring.

## Expected behavior

Executing `cljr-clean-ns` in a CLJS/CLJC file should clean the namespace.

## Actual behavior

An emacs error condition, with the following error in the *Messages* buffer:

```
if: Don’t know how to create ISeq from: clojure.core$memoize$fn__6894
```

## Steps to reproduce the problem

`cider-jack-in-cljs` to a project, open a namespace and run `cljr-clean-ns`.

I also tried this on an old CLJ project and encountered the same error. It *seemed* like it may have run successfully the first time but not on subsequent invocations?

### clj-refactor.el and refactor-nrepl version information

clj-refactor 3.3.0 (package: 20220207.2352), refactor-nrepl 3.3.0

#### For CLJS
```
;; Connected to nREPL server - nrepl://localhost:42119
;; CIDER 1.3.0-snapshot, nREPL 0.9.0
;; Clojure 1.10.3, Java 1.8.0_312
;;  Startup: /usr/local/bin/clojure -Sdeps '{:deps {nrepl/nrepl {:mvn/version "0.9.0"} cider/piggieback {:mvn/version "0.5.2"} refactor-nrepl/refactor-nrepl {:mvn/version "3.3.0"} cider/cider-nrepl {:mvn/version "0.28.1"}} :aliases {:cider/nrepl {:main-opts ["-m" "nrepl.cmdline" "--middleware" "[refactor-nrepl.middleware/wrap-refactor,cider.nrepl/cider-middleware,cider.piggieback/wrap-cljs-repl]"]}}}' -Mdev:cider/nrepl
```

#### For CLJ:

```
;; Connected to nREPL server - nrepl://localhost:40225
;; CIDER 1.3.0-snapshot, nREPL 0.9.0
;;  Startup: /usr/local/bin/clojure -A:perf -Sdeps '{:deps {nrepl/nrepl {:mvn/version "0.9.0"} refactor-nrepl/refactor-nrepl {:mvn/version "3.3.0"} cider/cider-nrepl {:mvn/version "0.28.1"}} :aliases {:cider/nrepl {:main-opts ["-m" "nrepl.cmdline" "--middleware" "[refactor-nrepl.middleware/wrap-refactor,cider.nrepl/cider-middleware]"]}}}' -M:cider/nrepl
```

### Emacs version

GNU Emacs 29.0.50 (build 6, x86_64-pc-linux-gnu, GTK+ Version 3.24.20, cairo version 1.16.0) of 2022-02-07

### Operating system

Ubuntu Linux 20.04

**Comment by vemv** [comment]
Checking out, thanks for the report

**Comment by vemv** [comment]
refactor-nrepl + clj-refactor.el 3.3.1 have been released (it can take a couple hours for melpa to pick up the latter).

Thanks again for the report!

**Comment by dgtized** [comment]
Thanks so much for the fix!
