### ISSUE TITLE
Get rid of pomegranate

### ISSUE THREAD

**Issue by expez** [clojure-emacs/refactor-nrepl#37]
This dependency is causing too many problems.

**Comment by benedekfazekas** [comment]
nice! what happens if alembic is not present tho?

**Comment by expez** [comment]
if you don't follow the instructions in the readme, and provide alembic, you won't be able to start a repl.

**Comment by expez** [comment]
I tried adding alembic as a proper dependency in `refactor-nrepl` which I'd much prefer but `lein repl` would just complain about not finding alembic on the classpath until I added it as a dependency in the manner described in our (and the alembic) readme.

If you want to look into why this is so that would be a 'nice to have' but this isn't such a big deal imo.

**Comment by benedekfazekas** [comment]
will have a look. missed the readme bit. sry

**Comment by expez** [comment]
A new snapshot with this fix is now on clojars.

**Comment by benedekfazekas** [comment]
alembic removed from provided and added as regular deps. needed a bit of hacking on mranderson (pls check the refactor-nrepl readme. also `build.sh` added for easier mrandersoning...

no need to add alembic to your profiles or whatever... cc @rundis
