### ISSUE TITLE
artifact-versions returns empty result with 0.3.0-SNAPSHOT (...-20)

### ISSUE THREAD

**Issue by rundis** [clojure-emacs/refactor-nrepl#38]
Trying out the latest snapshot as of now (.20 version), and the artifact-versions op now results empty when results are expected.

**Comment by expez** [comment]
`artifact-list` always precedes `artifact-versions` in `clj-refactor`.  The empty list is reasonable if you call `artifact-versions` first or in parallel.  Is that what happened?

I'll add a guard to the op.

**Comment by expez** [comment]
snapshot 21 is out!
