### ISSUE TITLE
Honor namespace local configuration of clj-kondo

### ISSUE THREAD

**Issue by OknoLombarda** [clojure-emacs/refactor-nrepl#387]
refactor-nrepl [already honors](https://github.com/clojure-emacs/refactor-nrepl/pull/361) clj-kondo's global config for unused namespaces, but maybe it would be right to also check [namespace local configuration](https://github.com/clj-kondo/clj-kondo/blob/master/doc/config.md#namespace-local-configuration)?

**Comment by vemv** [comment]
I'd be fine with this, thanks for the proposal!

**Comment by vemv** [comment]
@OknoLombarda: did you have in mind to offer a PR?

**Comment by OknoLombarda** [comment]
Yeah, I just don't have much time lately. I'll try to do it on this weekend. Also, clj-kondo supports namespace local configuration via namespace metadata, but that's probably gonna be too much? I guess I'll just add `:config-in-ns` support, at least for now

**Comment by vemv** [comment]
Sweet!

Both are nice, but any contribution is welcome!
