### ISSUE TITLE
rename find-debug-invocations

### ISSUE THREAD

**Issue by expez** [clojure-emacs/refactor-nrepl#41]
I think the old name hints too much at the intended usage and I'd like something more general like `find-usages-bulk` if there's time before 1.0.

**Comment by benedekfazekas** [comment]
tbh this might be just a duplum of find symbols... I will check and most likely remove this. and reimplement the remove functionality in the client based on find symbols.

**Comment by expez** [comment]
Instead of walking the AST `n` times it walks it once checking for `n` things.  The difference in speed might matter.
