### ISSUE TITLE
rename-symbol returns empty-like results ?

### ISSUE THREAD

**Issue by rundis** [clojure-emacs/refactor-nrepl#44]
Context:
I invoke something like this from LT:
```clojure
(do (require 'refactor-nrepl.client) (require 'clojure.tools.nrepl) (require 'lighttable.nrepl.eval) (def z-ns 'acme-auth.store) (def tr (refactor-nrepl.client/connect)) (refactor-nrepl.client/rename-symbol   :transport tr :ns z-ns :name "add-user!" :new-name "dill"))
```
1) If I do a successfull rename (it actually renames two occurrences)
- but the result I get back from the invocation above is (nil nil), no status response item either.

2) If I mangle one of the namespaces involved in the rename
I get an empty list as result, but no status etc here either.

When I call find symbol I don't go through the `refactor-nrepl.client`, but that works like a charm with error messages and the whole sheebang.

Maybe there is something I'm missing ?

**Comment by rundis** [comment]
hmm, tried calling find-symbol through the client, and that does either 
- return a a formatted/colorized reply (without all the metadata goodies etc), so I guess the client is not really what I need.
- or an empty list if something fails

neither of which is what I need :) So the client isn't really what I'm looking for I suppose. Maybe I'm better of implementing the rename part on the LT side of things then ?

**Comment by expez** [comment]
@rundis the idea behind the client is to expose some of the operations in the repl for users of the editors that haven't created their own nrepl client yet.

We've implementing the renaming in `clj-refactor` for emacs and you should probably do the same for lt.

**Comment by benedekfazekas** [comment]
yeah as @expez says the built in clojure client is more for demo reasons, showing for possible client developers how to use the middleware. secondly you can use it from the repl. i guess your case is somewhat special @rundis as ur client is essentially a clojure one. i still prefer a smoothly working clj client so i will check these problems

**Comment by rundis** [comment]
Got it ! I didn' t read the client section introduction (which is pretty clear on its purpose btw).

**Comment by benedekfazekas** [comment]
still what you say means that the client is broken currently. so that I will deffo have a closer look what's going on there

**Comment by benedekfazekas** [comment]
ok checking the code I dont see anything wrong with the client. it just works as a client does not return the the result from the middleware. so this is a close
