### ISSUE TITLE
find-unbound messes up in certain situations

### ISSUE THREAD

**Issue by expez** [clojure-emacs/refactor-nrepl#48]
Not sure what's special here, but @rundis found this, where `|` indicates the cursor:

```clj
(ns acme-auth.store
  (:require [clojure.java.jdbc :as jdbc]))
 
(defn- find-user-roles [conn user-id]
  (let [id (|jdbc/query conn "select sysdate from dual")]
    (map (fn [row] {:role-id (:id row) :application-id (:application_id row)})
         (jdbc/query conn ["select r.id, r.application_id
                           from role r
                           inner join user_role ur on r.id = ur.role_id
                           where ur.user_id = ?" user-id]))))
```

This results in unbound of `[conn user-id]` but only `conn` is used.

**Comment by benedekfazekas** [comment]
ack. will have a look

**Comment by benedekfazekas** [comment]
i have a fix for the problem quoted here. but i grew a bit uneasy about my approach on finding the AST node based on the cursor location.

@expez @rundis what would you expect to happen if cursor had been placed
- two chars before quoted just after `id`
- between the sql string and `user-id`
?

**Comment by expez** [comment]
`[id |(jdbc/query conn "select sysdate from dual")]` => `[id conn]`

`["select r.id, r.application_id
                           from role r
                           inner join user_role ur on r.id = ur.role_id
                           where ur.user_id = ?" | user-id]` => [user-id]

**Comment by benedekfazekas** [comment]
does it make sense to extract the binding part out of the let into an fn? I guess it does not

**Comment by expez** [comment]
yeah, it's a nonsense query but in a different context this could be the creation of a regular vector

**Comment by benedekfazekas** [comment]
yeah, should we be so very nice to handle this case?

**Comment by expez** [comment]
Is the extraction of a vector in the context of a `let` different somehow?  If so, then it's probably  not worth the effort.

The function below is returning a vector, which is a pair, and then for whatever reason the creation of this pair is extracted out into it's own function.

```clj
(defn foo [bar baz]
...
  [:keyword | (frobnicate baz)]
```

I'd like that to work.

**Comment by benedekfazekas** [comment]
yeah basically the second case with the cursor in the vector with `user-id` and the sql string. agreed. i'd like this to work too :(

in fact it seems it really kinda depends for these edge cases where the cursor is positioned. this really sucks
