### ISSUE TITLE
clean-ns  should use :err not :error to be consistent with other ops

### ISSUE THREAD

**Issue by rundis** [clojure-emacs/refactor-nrepl#54]

**Comment by expez** [comment]
These are two different things. `:err` are handled by `CIDER` in emacs.  These messages are unhandled exceptions where an ugly stacktrace is shown to the user and somebody comes on github to open a ticket.

`error` are problems the user can do something about, like trying to run refactorings on a project which is in such a bad state we cannot build an ast or if they try to run `clean-ns` on a `:use` clause containing an `:exclude` clause.  These all contain a message which I've intended to show to the user.

**Comment by rundis** [comment]
Ok. I see.  
Might be worth a mention in the readme eventually.

But how about this from find-unbound then ?:

```({:result ({:status [done find-unbound-error], :ex class java.lang.IllegalStateException, :id 206b973c-7bf1-4134-beea-e4cb29f92f11, :err java.lang.IllegalStateException: acme-auth.store is in a bad state!
 at refactor_nrepl.analyzer$ns_ast.invoke (analyzer.clj:75)```

This one might be a user error or programming error, depending on the eye of the beholder I suppose.
If I provide an illegal version number (ie one that doesn't exist in clojars) for hotload-dependency

```({:status [done hotload-dependency-error], :ex class java.lang.reflect.InvocationTargetException, :id 0ccbe89e-6ac5-4bce-ba66-06be07ab3ab2, :err java.lang.reflect.InvocationTargetException: null
....
Caused by: org.sonatype.aether.resolution.DependencyResolutionException: Could not find artifact buddy:buddy-sign:jar:0.3.09 in clojars (http://clojars.org/repo)```

**Comment by benedekfazekas** [comment]
both should be `:error` I guess. first one is an user error in the sense that we can't do certain things for which we need to analyze a given namespace which needs to be valid.

**Comment by expez** [comment]
@rundis the first one should be fixed on `master` and should return only `acme-auth.store is in a bad state!` under the `:error` key.

The second one should, ideally, also return under `:error`, but mapping all exceptions to helpful error messages is something we just haven't gotten around to yet. 

Furhtermore, the last error is impossible to provoke with `clj-refactor` because the user is prompted to select from a list of valid artifacts and then prompted to select from a valid list of versions.

**Comment by rundis** [comment]
First: cool.

Second: i completely understand that mapping all kinds of underlying (relevant) exceptions to user friendly ones, is not feasible and in some cases not even relevant. 
Btw i also prompt for the version, but haven't figured out a smooth solution for stopping the user from modifying the version once added as text in the editor (nor would i want to stop users from manually pasting dep-vectors etc. So in my case this ex is bound to happen to some users. 
In any case they get the whole trace so they should be able to figure it out. No biggie, but if you like i could file a separate low priority issue to catch this one in particular ?

**Comment by expez** [comment]
> if you like i could file a separate low priority issue to catch this one in particular ?

Certainly!  It's very much in scope for `refactor-nrepl` to be usable--and user friendly!--for other clients than `clj-refactor`!
