### ISSUE TITLE
<! is removed by clean-ns 

### ISSUE THREAD

**Issue by expez** [clojure-emacs/refactor-nrepl#57]
`<!` is a function and is removed by the surrounding `go` macro so it doesn't show up in the AST.  As it's not a macro we're not checking for it in the 'macro pass' either.

**Comment by expez** [comment]
Messed up the commit message, but I think I got this one now.

`clean-ns` is becoming more and more conservative, but I can't think of another way to solve this.

**Comment by magnars** [comment]
I think conservative is a good stance for clean-ns. :+1:
