### ISSUE TITLE
Rename refactoring

### ISSUE THREAD

**Issue by expez** [clojure-emacs/refactor-nrepl#6]
I think the most valuable refactoring we haven't tackled yet is that of renaming stuff.  Does anyone have any thoughts on how this should work?  What happens if you try to analyze source that is invalid?  I'm thinking it might be easy to get into a situation where we can find 99% of the occurrences of an identifier but miss one or two due to syntax errors in the file.

We've previously talked a bit about how we're going to tackle undo when we're doing refactoring in the middlewere and this might be difficult for this feature.  I propose we just do like `ternjs` does: drop undo and instead just let the user rename it once again to undo the operation.  When you rename something using tern it will give just prompt your for the new name instead of letting you edit inline with multiple cursors or whatever.

@AlexBaranosky any interest in continuing [your explorations](https://github.com/clojure-emacs/clj-refactor.el/issues/11)?

**Comment by narendraj9** [comment]
@benedekfazekas 

I am trying to understand what `node->var` is doing. Why do we need to check `:class`? 
For `:op :catch` type AST nodes, `:class` is a map. Sometimes, this map is so huge that I get Java Heap Out of Memory exception while doing a `join`

Can you please help me understand what the intention is with using `:class`?
