### ISSUE TITLE
find-usages (and clean-ns ?) messes with file info in var meta

### ISSUE THREAD

**Issue by rundis** [clojure-emacs/refactor-nrepl#65]
Before running find-usages on a freshly connected project the following snippet returns sane file references: 
```
(doseq [v (vals (ns-interns `acme-auth.store))]
   (println (meta v)))
```

After running the find-usages op the file references for the above snippet returns the location of a temp file. Alone the lines of:
```
{:ns #<Namespace acme-auth.store>, :name invalidate-token!, :file /private/var/folders/c7/_w_4f1617dvbdkcx17ppnpfw0000gn/T/form-init8517234393706252752.clj, :end-column 66, :column 1, :line 57, :end-line 64, :arglists ([conn id] [conn user-id issued])}
```

Evaling the file put things right, or using tools.namespace.repl/refresh also get things back to normality.
I believe @benedekfazekas verified this in a repl session as well.

**Comment by expez** [comment]
@Bronsa is this caused by our running tools.analyzer?

**Comment by benedekfazekas** [comment]
or can we possibly pass in some extra information to the analyzer to fix this?

**Comment by benedekfazekas** [comment]
this

```clojure
(binding [*file* "/path/to/energy-market/src/energy_market/config.clj"]
  (type (aj/analyze-ns 'energy-market.config)))
```

seems to solve the problem. wonder if it is the right way to do this?

**Comment by benedekfazekas** [comment]
@Bronsa pls verify that this is the right way to do this, thx

**Comment by Bronsa** [comment]
this was a bug in tools.analyzer, fixed with this commit: https://github.com/clojure/tools.analyzer.jvm/commit/94b0b903d2dbf0cf91d45e55bfe3bfc0a7a2acec (same fix as the one implemented yourself)
I'm not going to release 0.6.7 in a while so it's best if you just keep binding *file* yourselves, thanks for letting me know about this!

**Comment by benedekfazekas** [comment]
np @Bronsa. fix is on clojars
