### ISSUE TITLE
mranderson deps appear in resolve-missing

### ISSUE THREAD

**Issue by expez** [clojure-emacs/refactor-nrepl#66]
The `LT` plugin is currently filtering these out but we should do it in the middleware as it's affecting all clients.

**Comment by rundis** [comment]
That would be nice. I guess cider-nrepl might deserve an issue or two for the same concern ?

**Comment by benedekfazekas** [comment]
i raised the same point. but acc. to @expez that is not an issue there...

**Comment by expez** [comment]
You convinced me it might be, so I opened an issue for the other contributors to chime in.
