### ISSUE TITLE
refactor-nrepl's Clojure dependency (1.5.1) can override version specified by other project dependencies

### ISSUE THREAD

**Issue by samroberton** [clojure-emacs/refactor-nrepl#72]
I have a project whose `project.clj` doesn't directly specify an `org.clojure/clojure` dependency in its `:dependencies` vector.  (I have multiple related leiningen projects, and I want to specify the version of Clojure in only the most-upstream project, and have that trickle downstream to the rest.)

I have `refactor-nrepl` in my user `profiles.clj`'s `:plugins` vector.

Because the `refactor-nrepl` plugin adds itself as a project dependency when `lein` loads up, `lein` is seeing that my `project.clj` is not itself directly specifying a Clojure dependency, but that I have multiple dependencies which *do* specify a Clojure version --- and it's resolving the conflicting versions by picking the version that `refactor-nrepl` wants, which leaves my project using Clojure 1.5.1 instead of the version I specify in my other upstream project (1.6.0).

Obviously I can work around this by putting a specific Clojure dependency in all my projects, but it seems like undesirable behaviour for `refactor-nrepl`.  I haven't actually tested this, but I suspect that putting the `refactor-nrepl` Clojure dependency in the `provided` scope (ie moving the `:dependencies` vector into a `:provided` profile) would probably solve the problem.  Alternatively, it might be reasonable the `refactor-nrepl.plugin/middleware` add the `refactor-nrepl` dependency with `:exclusions [org.clojure/clojure]`.

The same presumably applies for the `tools.nrepl` dependency.

Is that reasonable?

**Comment by benedekfazekas** [comment]
it is absolutely reasonable. thanks for the suggestions too
