### ISSUE TITLE
find-symbol returns false positives for functions used in macros

### ISSUE THREAD

**Issue by expez** [clojure-emacs/refactor-nrepl#79]
When the function being searched for occurs in a macro we return the location of the macro. 

We should filter out hits where the function being searched for doesn't appear in the source file at the hit of the location.  If we don't do this in the middleware every client has to re-implement this filtering because in a refactoring context these are false positives (they can't be used for renaming, and they don't belong in a "find usages" buffer).

**Comment by benedekfazekas** [comment]
this is related to #47 and maybe fixed if that is fixed (or the other way around)

**Comment by expez** [comment]
Awesome! :+1:

**Comment by benedekfazekas** [comment]
will need a small tweak. will do in the evening
