### ISSUE TITLE
warning

### ISSUE THREAD

**Issue by sonwh98** [clojure-emacs/refactor-nrepl#83]
; CIDER 0.9.0snapshot (package: 20150608.1018) (Java 1.8.0_25, Clojure 1.6.0, nREPL 0.2.10)
WARNING: The following nREPL ops are not supported:                                                                                                                               
artifact-list artifact-versions clean-ns configure find-symbol find-unbound hotload-dependency resolve-missing version                                                            
Please, install (or update) refactor-nrepl and restart CIDER.                                                                                                                     
You can mute this warning by changing cljr-suppress-middleware-warnings.

my ~/.lein/profiles.clj is

{:user {:plugins [[lein-cljsbuild "1.0.5"]
                  [lein-figwheel "0.3.3"]
                  [cider/cider-nrepl "0.9.0-SNAPSHOT"]
                  [refactor-nrepl "1.1.0-SNAPSHOT"]]
        :dependencies [[org.clojure/tools.nrepl "0.2.10"]]}}

any idea why this warning is happening?

**Comment by benedekfazekas** [comment]
what is your clj-refactor.el version?

**Comment by sonwh98** [comment]
clj-refactor is an installed package.

     Status: Installed in `~/.emacs.d/elpa/clj-refactor-20150607.501/' (unsigned).
    Archive: n/a
    Version: 20150607.501
   Requires: emacs-24.3, s-1.8.0, dash-2.4.0, yasnippet-0.6.1, paredit-24,
               multiple-cursors-1.2.2, cider-0.8.1, edn-1.1.1
    Summary: A collection of clojure refactoring functions
   Keywords: [convenience]
    Other versions: 20150607.501 (melpa).

**Comment by benedekfazekas** [comment]
everything seems to be in order. weird. anything unusual, or exception in your nrepl-server buffer? also can you pls add `(setq nrepl-log-messages t)` to your emacs config, restart your cider repl and post the contents of `*nrepl-messages*` buffer.

**Comment by sonwh98** [comment]
thanks for your help. I don't have an nrepl-server buffer when starting lein figwheel. Here is my nrepl-message buffer:

(--->
  op  "clone"
  id  "1"
)
(<-
  id  "1"
  new-session  "4631466f-8986-4946-aa41-52506f02e0d6"
  session  "8c721408-9b49-4b37-ba58-0eddb033972a"
  status  ("done")
)
(--->
  op  "clone"
  id  "2"
)
(<-
  id  "2"
  new-session  "c65b04b9-fc28-43cb-81c6-d2b5aab5a550"
  session  "dcb2c7ff-a3db-42c6-aee5-3e4ce2c8fa5c"
  status  ("done")
)
(--->
  op  "describe"
  id  "3"
)
(<-
  aux  (dict
         current-ns  "user"
       )
  id  "3"
  ops  (dict
         apropos  (dict)
         classpath  (dict)
         clone  (dict)
         close  (dict)
         complete  (dict)
         complete-doc  (dict)
         debug-input  (dict)
         describe  (dict)
         eldoc  (dict)
         eval  (dict)
         format-code  (dict)
         format-edn  (dict)
         info  (dict)
         init-debugger  (dict)
         inspect-pop  (dict)
         inspect-push  (dict)
         inspect-refresh  (dict)
         interrupt  (dict)
         load-file  (dict)
         ls-sessions  (dict)
         macroexpand  (dict)
         ns-list  (dict)
         ns-path  (dict)
         ns-vars  (dict)
         pprint-middleware  (dict)
         refresh  (dict)
         refresh-all  (dict)
         resource  (dict)
         resources-list  (dict)
         retest  (dict)
         stacktrace  (dict)
         stdin  (dict)
         test  (dict)
         test-stacktrace  (dict)
         toggle-trace-ns  (dict)
         toggle-trace-var  (dict)
         undef  (dict)
       )
  session  "96aae702-124a-4a67-9c85-c17dd226bc85"
  status  ("done")
  versions  (dict
              clojure  (dict
                         incremental  0
                         major  1
                         minor  7
                         qualifier  "RC1"
                         version-string  "1.7.0-RC1"
                       )
              java  (dict
                      incremental  "0"
                      major  "1"
                      minor  "8"
                      update  "25"
                      version-string  "1.8.0_25"
                    )
              nrepl  (dict
                       incremental  "10"
                       major  "0"
                       minor  "2"
                       qualifier  ""
                       version-string  "0.2.10"
                     )
            )
)
(--->
  op  "eval"
  session  "4631466f-8986-4946-aa41-52506f02e0d6"
  code  "(str *ns*)"
  id  "4"
)
(<-
  id  "4"
  ns  "user"
  session  "4631466f-8986-4946-aa41-52506f02e0d6"
  value  "\"user\""
)
(<-
  id  "4"
  session  "4631466f-8986-4946-aa41-52506f02e0d6"
  status  ("done")
)
(--->
  op  "eval"
  session  "4631466f-8986-4946-aa41-52506f02e0d6"
  code  "(when (clojure.core/resolve 'clojure.main/repl-requires)\n      (clojure.core/map clojure.core/require clojure.main/repl-requires))"
  id  "5"
)
(--->
  op  "eval"
  session  "4631466f-8986-4946-aa41-52506f02e0d6"
  code  "(try\n      (require 'cider.nrepl.version)\n      (:version-string @(resolve 'cider.nrepl.version/version))\n    (catch Throwable _ \"not installed\"))"
  id  "6"
)
(<-
  id  "5"
  ns  "user"
  session  "4631466f-8986-4946-aa41-52506f02e0d6"
  value  "(nil nil nil)"
)
(<-
  id  "5"
  session  "4631466f-8986-4946-aa41-52506f02e0d6"
  status  ("done")
)
(<-
  id  "6"
  ns  "user"
  session  "4631466f-8986-4946-aa41-52506f02e0d6"
  value  "\"0.9.0-snapshot\""
)
(<-
  id  "6"
  session  "4631466f-8986-4946-aa41-52506f02e0d6"
  status  ("done")
)

**Comment by benedekfazekas** [comment]
hm... i am not really sure what is going on here. I am not sure at all what happens repl and nrepl middleware wise when you run `lein figwheel`. I don't use figwheel myself and reading its documentation and ciders it is not clear to me that even cider support figwheel.

out of curiosity: do you have the same warning when you jack-in on a good old .clj file on a clojure project?

**Comment by sonwh98** [comment]
I deleted my ~/.emacs and started over with a clean slate and the warning went away. 
I just realize that refactor-nrepl will only work with nrepl base projects. clojurescript doesn't use nrepl. It has its own repl that connects to the web browser. Is there a chance that the advance  features be made independent of the nrepl? Stuff like find-usage and extract method is useful in clojurescript too but its not available because of the dependency on nrepl

**Comment by expez** [comment]
> Is there a chance that the advance features be made independent of the nrepl? 

I want to get boot support in the future at the very least.

> Stuff like find-usage and extract method is useful in clojurescript too but its not available because of the dependency on nrepl

It's not just about nrepl, right now `refactor-nrepl` doesn't understand clojurescript at all (because nobody involved in the project writes much clojurescript).  We'd need to swap in `tools.analyzer.js` instead of `tools.analyzer.jvm` in order to get `find-usages` etc to work also for clojurescript.  This may or may not be easy :)
