### ISSUE TITLE
cljr--maybe-rethrow-error: Can't find interface rep.backend.db/UserStore

### ISSUE THREAD

**Issue by benedekfazekas** [clojure-emacs/refactor-nrepl#84]
discussion with @adulteratedjedi on slack:

Given the contrived example of

```clojure
(defprotocol UserStore
  "Just a test user store"
  (create-user [user])
  (delete-user [user]))

(defrecord User [username]
  UserStore)
```

I get cljr--maybe-rethrow-error: Can't find interface rep.backend.db/UserStore .. Saved and loaded into the repl fine

**Comment by expez** [comment]
I assume the refactoring in question is `cljr-add-stubs`.  I just tried running that refactoring, copy-pasting this code, and it worked just fine.

I recently fixed a bug where the client would send the wrong information down to the server if `UserStore` was defined in some other namespace and the refactoring was called on say `users/UserStore`.
