### ISSUE TITLE
rename find-unbound to find-used-locals

### ISSUE THREAD

**Issue by benedekfazekas** [clojure-emacs/refactor-nrepl#86]
better name as there is no negation in it and describes the op better.

keep the old `find-unbound` around for a while as well with a deprecated warning as this rename will break clients

**Comment by expez** [comment]
The new name isn't any better and this change creates quite a bit of work with no reward.

The new name could be taken to mean "return a list of all local variables, filtering out any that aren't used". What the op really does is return a list of the unbound variables when the surrounding sexp is promoted to a be a toplevel form.

**Comment by benedekfazekas** [comment]
thx for the feedback. the only reward is clarity, mind you i appreciate judging clarity may not be an objective thing.

> "return a list of all local variables, filtering out any that aren't used"

well, that is what it does atm if we add that the context is a given/selected s-expression.

**Comment by benedekfazekas** [comment]
you might want to proof read the documentation update i've done for the this op in the README too btw

**Comment by expez** [comment]
> well, that is what it does atm if we add that the context is a given/selected s-expression.

Aight, suppose I wasn't entirely clear on this worked after the change.

Go ahead and rename it if you want and if it doesn't affect anyone else adversely.  I don't think this is used by anyone else yet.

> you might want to proof read the documentation update i've done for the this op in the README too btw

Looks good!  Thanks!
