### ISSUE TITLE
`cljr-slash` hangs Emacs and erases the buffer if there's a comment in the namespace.

### ISSUE THREAD

**Issue by Malabarba** [clojure-emacs/refactor-nrepl#90]
Place point after `walk` and hit `/`. Emascs will hang. 

    (ns binomial.core
      (:gen-class)
      (:require [clojure.string :as   s])
      ;; (:import mage.interfaces.MageClient
      ;;          mage.interfaces.MageServer)
      )

    (walk)

Hitting `C-g` will result in the following (yes, everything else is **deleted**).

    (ns binomial.core
      (:gen-class)
      (:require [clojure.string :as   s]
                [clojure.walk :as walk])
      ;; (:import

This doesn't happen if the commented `:import` has only one line.

Backtrace when hitting `C-g`:

    Debugger entered--Lisp error: (quit)
      syntax-ppss()
      beginning-of-defun-raw(nil)
      beginning-of-defun()
      paredit-current-parse-state()
      paredit-in-string-p()
      paredit-move-forward()
      paredit-forward()
      apply(paredit-forward nil)
      cljr--point-after(paredit-forward)
      cljr--delete-and-extract-sexp()
      cljr--extract-ns-statements(":import" nil)
      cljr-sort-ns()
      cljr--maybe-sort-ns()
      cljr-slash()
      funcall-interactively(cljr-slash)
      call-interactively(cljr-slash nil nil)
      command-execute(cljr-slash)

**Comment by benedekfazekas** [comment]
problem seems to be with `cljr-sort-ns` in fact you can reproduce the problem if you run sort ns (`sn`)

**Comment by benedekfazekas** [comment]
@magnars @expez any objection if i remove the `(cljr--maybe-sort-ns)` call from here as clean-ns is preferred anyway...?

**Comment by benedekfazekas** [comment]
@Malabarba thx for the report. as a temporary workaround you can switch off autosorting the ns declarartion with:
```emacs-lisp
(setq cljr-auto-sort-ns nil)
```
in your emacs config

**Comment by Malabarba** [comment]
@benedekfazekas Thanks, I'll do that.

**Comment by magnars** [comment]
It's obvious that clean-ns isn't enough, since it fails in cases like this - basically any time we want to help you out while you're in the middle of writing a piece of code. So my opinion is that we should continue supporting these simpler tools, not deprecate them.
