### ISSUE TITLE
Enabling refactor-nrepl causes sente+transit to break

### ISSUE THREAD

**Issue by jwr** [clojure-emacs/refactor-nrepl#93]
Ok, so I know this sounds weird, but after hours of bisecting my project.clj I narrowed it down: adding `[refactor-nrepl "1.0.5"]` to my :plugins in project.clj and running from cider (cider-jack-in) causes my app to break. More specifically, it breaks somewhere in transit/sente (I am not 100% sure which), as the backtrace isn't terribly informative:

```
                                            java.lang.Thread.run                       Thread.java:  745
              java.util.concurrent.ThreadPoolExecutor$Worker.run           ThreadPoolExecutor.java:  617
               java.util.concurrent.ThreadPoolExecutor.runWorker           ThreadPoolExecutor.java: 1142
                                                             ...                                        
           clojure.core.async.impl.channels.ManyToManyChannel/fn                      channels.clj:  102
                                clojure.core.async/do-alts/fn/fn                         async.clj:  231
                                 clojure.core.async/ioc-alts!/fn                         async.clj:  362
    clojure.core.async.impl.ioc-macros/run-state-machine-wrapped                    ioc_macros.clj:  944
            clojure.core.async.impl.ioc-macros/run-state-machine                    ioc_macros.clj:  940
      taoensso.sente/start-chsk-router!/fn/state-machine--auto--                         sente.clj: 1144
   taoensso.sente/start-chsk-router!/fn/state-machine--auto--/fn                         sente.clj: 1151
taoensso.sente/start-chsk-router!/fn/state-machine--auto--/fn/fn                         sente.clj: 1157
                         partsbox.server/sente-event-msg-handler  form-init3859442600605537156.clj:   43
              taoensso.sente/make-channel-socket!/fn/fn/reply-fn                         sente.clj:  553
                                                             ...                                        
                                             taoensso.sente/pack                         sente.clj:  236
                                              clojure.core/apply                          core.clj:  630
                                                             ...                                        
                                            taoensso.sente/pack*                         sente.clj:  233
                 taoensso.sente.packers.transit.FlexiPacker/pack                       transit.clj:   83
                            taoensso.sente.packers.transit/fn/fn                       transit.clj:   59
                                              clojure.core/apply                          core.clj:  632
                                                             ...                                        
                                            clojure.core/max-key                          core.clj: 4790
                                            clojure.core/max-key                          core.clj: 4788
                                                             ...                                        
java.lang.NullPointerException: 
```

This happens only when I run the app through cider-jack-in. Running it with lein-repl does not cause the problem to appear. So, it would seem that this happens only if cider contacts refactor-nrepl and enables it.

I don't know how to trace it down further, but perhaps this will give you some ideas?

**Comment by expez** [comment]
What's your version of cider?

**Comment by jwr** [comment]
I'm using `[cider/cider-nrepl "0.9.1"]`, along with cider 0.9.1, obviously.

**Comment by expez** [comment]
@bbatsov any thoughts on how `cider-jack-in` is different from `lein repl`?

It breaks when you try to bring up the repl?

**Comment by bbatsov** [comment]
Nothing special there - it just runs `lein repl :headless` by default. I'm guessing the direction in which the command is invoked might be related to this, but I can't be sure.

**Comment by jwr** [comment]
The app breaks also if I run `lein repl` and then use `cider-connect` to connect to it (although I don't see the backtrace then).

The app does not break if `refactor-nrepl` is included in `:plugins`, but I use `lein repl` and do not connect using cider.

It seems that to reproduce the problem I have to actually use `cider`, either by doing `cider-jack-in` or `cider-connect`. It isn't enough to just include the `refactor-nrepl` in `project.clj`.

**Comment by expez** [comment]
Could this be caused by `CIDER` and `Sente` stepping on eachothers ports?

Do you have any other ideas about the cause, @ptaoussanis?

**Comment by jwr** [comment]
@expez: Sente doesn't use the same port. Also, please note that I use cider regularly, it's only the addition of `refactor-nrepl` to my `project.clj` that causes problems.

If there are no ideas at all, I could try to dig in, but this is one of those problems that seems extremely hard to get to.

**Comment by ptaoussanis** [comment]
> Do you have any other ideas about the cause, @ptaoussanis?

@jwr Could you maybe try this with `[com.taoensso/sente "1.6.0-beta1"]`? I'm not at all familiar with refactor-nrepl, but I'm guessing it might be doing something unexpected to the Clojure reader bindings? 1.6.0-beta1 includes a binding reset so might be worth trying.

**Comment by jwr** [comment]
@ptaoussanis: I just tried it, and I still get the same NullPointerException with `1.6.0-beta1`.

**Comment by ptaoussanis** [comment]
@jwr And if you turn off the Transit packer for Sente (i.e. just use the default `:edn` packer)?

**Comment by jwr** [comment]
@ptaoussanis Switching from Transit to `:edn` makes the problem go away. Switching back to `{:packer (sente-transit/get-flexi-packer :edn)}` brings the problem back.

**Comment by ptaoussanis** [comment]
So sounds like something in `refactor-nrepl` might be interacting with Transit specifically?

@expez Is that helpful at all?

**Comment by expez** [comment]
`refactor-nrepl` doesn't have any explicit knowledge of `Transit`.  We recently solved a problem where we couldn't build an abstract syntax tree because we only used the default value of `*data-readers*`.   I'm guessing `Transit` has its own reader tags.   Could you try upgrading to `1.1.0` to see if that solves your problem, @jwr?

**Comment by jwr** [comment]
I'm happy to report that the problem does not show up under `1.1.0`. That seems to have fixed the problem.

@ptaoussanis, sorry for bothering you with this!

**Comment by ptaoussanis** [comment]
No problem, happy you found a solution! Cheers :-)

**Comment by jwr** [comment]
Well, I just upgraded clj-refactor inside Emacs to 1.1.0 and the problem is back.

To summarize:

* refactor-nrepl 1.0.4 + clj-refactor-1.0.4 — problem exists
* refactor-nrepl 1.1.0 + clj-refactor-1.0.4 — problem disappeared
* refactor-nrepl 1.1.0 + clj-refactor-1.1.0 — problem exists (again)

I am not sure now to reopen this issue.

**Comment by expez** [comment]
I can't think of any reason why upgrading `clj-refactor.el` is problematic.

To be clear, this is what happens:

1. lein repl brings up a repl
2. cider-connect
3. The terminal repl crashes with that terrible stacktrace

Or 

1. cider-jack-in
2. No repl, terrible stacktrace

If you do put this in your config: 

```el 
(setq cljr-eagerly-build-asts-on-startup nil
      cljr-auto-clean-ns nil)
```

Then you can bring up a repl, right?  But when you try to do `cljr-find-usages` you get a stacktrace?

**Comment by jwr** [comment]
No, the stacktrace (nullpointerexception) happens when my app packs a large data structure using transit and tries to send it. Just starting up using either lein repl or cider-jack-in is fine.

I will try to narrow it down some more. Just wanted to report that the issue came back.

**Comment by expez** [comment]
@jwr perhaps the newly released [lein-collisions](https://github.com/webnf/lein-collisions) can help uncover something fishy
