### ISSUE TITLE
find-unbound gets confused when destructuring is involved

### ISSUE THREAD

**Issue by expez** [clojure-emacs/refactor-nrepl#95]
```clj
(defn- libspec-in-use?
  [{:keys [ns as refer] :as libspec} symbols-in-file current-ns]
  (when (if (= refer :all)
          (some (partial ns-in-use-with-refer-all? current-ns ns) symbols-in-file)
          (some (fn [symbol-in-file]
                  (or
                   ;; Used through refer clause
                   (and (not= refer :all) (some (set (map str refer)) symbol-in-file))
                   ;; Used as a fully qualified symbol
                   (.startsWith symbol-in-file (str ns "/"))
                   ;; Aliased symbol in use
                   (and as (.startsWith symbol-in-file (str as "/")))))
                symbols-in-file))
    libspec))
```

When I run `cljr-promote-function` it doesn't recognize `ns` ,`as` or `refer` as something that has to be passed in as an argument in this new lexical context.

**Comment by benedekfazekas** [comment]
thx will have a look

**Comment by benedekfazekas** [comment]
can't reproduce. tested with:

```clojure
(defn some-fn-with-destruct [{:keys [foo bar]} things]
  (map (fn [thing] (println foo bar thing)) things))
```
when i promote the fn i get:
```clojure
(defn- thing-handler
  [foo bar thing]
  (println foo bar thing))

(defn some-fn-with-destruct [{:keys [foo bar]} things]
  (map (partial thing-handler foo bar) things))
```

which is what i expected. was not aware of the `partial` handling: really awesome!

the cursor location is wrong tho when multiple cursors is used (cc @magnars : tried to look at it but perhaps it is too late could not figure out how to control mc to put the cursor at the right place)

will close this if no objections...

**Comment by expez** [comment]
Yeah, this looks good now.  I think this might've been solved by this: https://github.com/clojure-emacs/clj-refactor.el/commit/2e0ea29838708b9d6c3c80aa6efbff4099b81487 

That is, I had the cursor on the `(` when I tried the refactoring back in the day.
