### ISSUE TITLE
Get rid of instaparse dependency

### ISSUE THREAD

**Issue by expez** [clojure-emacs/refactor-nrepl#98]
The instaparse dependency isn't really needed.  instaparse is super cool so I had a bad case of "hammer looking for nail" around the time I wrote `clean-ns` and just went with it.  Using a grammar to pull the ns form apart isn't going to scale when taking reader macros into account.  A better approach is to just read the ns form with a clj and cljs reader and pick it apart ourselves.

**Comment by magnars** [comment]
How will you maintain the reader macros with this approach?

**Comment by expez** [comment]
I don't see how we're going to be able to do any work and produce an ns form with reader macros in similar places.

The approach I expect to take is reading the ns form with the clj reader and then reading again with the cljs reader, doing our work and then building new `:require` and `:import` etc clauses by merging the results.

Thus, if you have `:refer [foo bar #?(:cljs baz)]` you'll probably get something less elegant because calculating the diff to find the smallest reader macro to insert seems like it's more work than it's worth.

I kind of like the approach intellij takes with java imports. They're not even shown by default and never something you think about but they're kept in good shape in the background (sorted, deduped and always actually being used).  

Some people might not take such a pragmatic view of the ns form and instead spend a great deal of time hand-crafting it with nicely aligned forms etc.  I don't think we'll ever be able to please this latter group so I'd rather target those that favor standardization, utility and automation like I do myself.

**Comment by magnars** [comment]
Sounds like an excellent approach. 👍
tor. 9. jul. 2015 kl. 14.50 skrev Lars Andersen <notifications@github.com>:
