### ISSUE TITLE
Configurable threading

### ISSUE THREAD

**Issue by Malabarba** [clojure-emacs/refactor-nrepl#99]
I always end up unwinding once after thread-first or thread-last. It would be nice to be able to specify a minimum depth or length of the first sexp in threading.

For instance, the following sexp

    (remove #(< value 0) (filter :name (map :items return)))

Expands to this

    (->> return
         (map :items)
         (filter :name)
         (remove #(< value 0)))

I'd like a way to say “the first line should be at least 1 level deep”, so it would end up like this:

    (->> (map :items return)
         (filter :name)
         (remove #(< value 0)))

**Comment by Malabarba** [comment]
As an extra bonus, it would be nice to have to specify a maximum length in characters for the first line. So that if the `return` variable has a very long name, it would still get its own line.

For instance, the following sexp

    (remove #(< value 0) (filter :name (map :items the.ns/of-a-long-var-name)))

Would then still expand to this

    (->> the.ns/of-a-long-var-name
         (map :items)
         (filter :name)
         (remove #(< value 0)))

**Comment by Malabarba** [comment]
Thanks!

**Comment by benedekfazekas** [comment]
np :)
